# coding: utf-8

# flake8: noqa
"""
    AviationStack

    The aviationstack API was built to provide a simple way of accessing global aviation data for real-time and historical flights as well as allow customers to tap into an extensive data set of airline routes and other up-to-date aviation-related information. Requests to the REST API are made using a straightforward HTTP GET URL structure and responses are provided in lightweight JSON format. The following API documentation can be applied for any major programming language and will present general integration guides and explanations around API endpoints, request parameters and response objects. If any questions remain unanswered for you, simply reach out to the aviationstack support team for assistance.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from swagger_client.models.air_craft_type_data import AirCraftTypeData
from swagger_client.models.air_craft_types import AirCraftTypes
from swagger_client.models.air_line_data import AirLineData
from swagger_client.models.air_lines import AirLines
from swagger_client.models.air_plane_data import AirPlaneData
from swagger_client.models.air_planes import AirPlanes
from swagger_client.models.airport_data import AirportData
from swagger_client.models.airports import Airports
from swagger_client.models.api_error import ApiError
from swagger_client.models.api_error_error import ApiErrorError
from swagger_client.models.cities import Cities
from swagger_client.models.city_data import CityData
from swagger_client.models.countries import Countries
from swagger_client.models.country_data import CountryData
from swagger_client.models.data_aircraft import DataAircraft
from swagger_client.models.data_airline import DataAirline
from swagger_client.models.data_departure import DataDeparture
from swagger_client.models.data_flight import DataFlight
from swagger_client.models.data_flight2 import DataFlight2
from swagger_client.models.data_flight2_codeshared import DataFlight2Codeshared
from swagger_client.models.data_routes import DataRoutes
from swagger_client.models.data_routes_flight import DataRoutesFlight
from swagger_client.models.datalive import Datalive
from swagger_client.models.flights import Flights
from swagger_client.models.flights_future import FlightsFuture
from swagger_client.models.future_flight_aircraft import FutureFlightAircraft
from swagger_client.models.future_flight_airline import FutureFlightAirline
from swagger_client.models.future_flight_data import FutureFlightData
from swagger_client.models.future_flight_data_codeshared import FutureFlightDataCodeshared
from swagger_client.models.future_flight_info import FutureFlightInfo
from swagger_client.models.future_flight_point import FutureFlightPoint
from swagger_client.models.pagination import Pagination
from swagger_client.models.route_airline import RouteAirline
from swagger_client.models.route_endpoint import RouteEndpoint
from swagger_client.models.routes import Routes
from swagger_client.models.tax_data import TaxData
from swagger_client.models.taxes import Taxes
from swagger_client.models.timetable import Timetable
from swagger_client.models.timetable_aircraft import TimetableAircraft
from swagger_client.models.timetable_airline import TimetableAirline
from swagger_client.models.timetable_data import TimetableData
from swagger_client.models.timetable_data_codeshared import TimetableDataCodeshared
from swagger_client.models.timetable_flight import TimetableFlight
from swagger_client.models.timetable_schedule import TimetableSchedule
