# coding: utf-8

"""
    AviationStack

    The aviationstack API was built to provide a simple way of accessing global aviation data for real-time and historical flights as well as allow customers to tap into an extensive data set of airline routes and other up-to-date aviation-related information. Requests to the REST API are made using a straightforward HTTP GET URL structure and responses are provided in lightweight JSON format. The following API documentation can be applied for any major programming language and will present general integration guides and explanations around API endpoints, request parameters and response objects. If any questions remain unanswered for you, simply reach out to the aviationstack support team for assistance.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AirLineData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'airline_id': 'str',
        'airline_name': 'str',
        'iata_code': 'str',
        'iata_prefix_accounting': 'str',
        'icao_code': 'str',
        'callsign': 'str',
        'type': 'str',
        'status': 'str',
        'fleet_size': 'str',
        'fleet_average_age': 'str',
        'date_founded': 'str',
        'hub_code': 'str',
        'country_name': 'str',
        'country_iso2': 'str'
    }

    attribute_map = {
        'id': 'id',
        'airline_id': 'airline_id',
        'airline_name': 'airline_name',
        'iata_code': 'iata_code',
        'iata_prefix_accounting': 'iata_prefix_accounting',
        'icao_code': 'icao_code',
        'callsign': 'callsign',
        'type': 'type',
        'status': 'status',
        'fleet_size': 'fleet_size',
        'fleet_average_age': 'fleet_average_age',
        'date_founded': 'date_founded',
        'hub_code': 'hub_code',
        'country_name': 'country_name',
        'country_iso2': 'country_iso2'
    }

    def __init__(self, id=None, airline_id=None, airline_name=None, iata_code=None, iata_prefix_accounting=None, icao_code=None, callsign=None, type=None, status=None, fleet_size=None, fleet_average_age=None, date_founded=None, hub_code=None, country_name=None, country_iso2=None):  # noqa: E501
        """AirLineData - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._airline_id = None
        self._airline_name = None
        self._iata_code = None
        self._iata_prefix_accounting = None
        self._icao_code = None
        self._callsign = None
        self._type = None
        self._status = None
        self._fleet_size = None
        self._fleet_average_age = None
        self._date_founded = None
        self._hub_code = None
        self._country_name = None
        self._country_iso2 = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if airline_id is not None:
            self.airline_id = airline_id
        if airline_name is not None:
            self.airline_name = airline_name
        if iata_code is not None:
            self.iata_code = iata_code
        if iata_prefix_accounting is not None:
            self.iata_prefix_accounting = iata_prefix_accounting
        if icao_code is not None:
            self.icao_code = icao_code
        if callsign is not None:
            self.callsign = callsign
        if type is not None:
            self.type = type
        if status is not None:
            self.status = status
        if fleet_size is not None:
            self.fleet_size = fleet_size
        if fleet_average_age is not None:
            self.fleet_average_age = fleet_average_age
        if date_founded is not None:
            self.date_founded = date_founded
        if hub_code is not None:
            self.hub_code = hub_code
        if country_name is not None:
            self.country_name = country_name
        if country_iso2 is not None:
            self.country_iso2 = country_iso2

    @property
    def id(self):
        """Gets the id of this AirLineData.  # noqa: E501


        :return: The id of this AirLineData.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this AirLineData.


        :param id: The id of this AirLineData.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def airline_id(self):
        """Gets the airline_id of this AirLineData.  # noqa: E501


        :return: The airline_id of this AirLineData.  # noqa: E501
        :rtype: str
        """
        return self._airline_id

    @airline_id.setter
    def airline_id(self, airline_id):
        """Sets the airline_id of this AirLineData.


        :param airline_id: The airline_id of this AirLineData.  # noqa: E501
        :type: str
        """

        self._airline_id = airline_id

    @property
    def airline_name(self):
        """Gets the airline_name of this AirLineData.  # noqa: E501


        :return: The airline_name of this AirLineData.  # noqa: E501
        :rtype: str
        """
        return self._airline_name

    @airline_name.setter
    def airline_name(self, airline_name):
        """Sets the airline_name of this AirLineData.


        :param airline_name: The airline_name of this AirLineData.  # noqa: E501
        :type: str
        """

        self._airline_name = airline_name

    @property
    def iata_code(self):
        """Gets the iata_code of this AirLineData.  # noqa: E501


        :return: The iata_code of this AirLineData.  # noqa: E501
        :rtype: str
        """
        return self._iata_code

    @iata_code.setter
    def iata_code(self, iata_code):
        """Sets the iata_code of this AirLineData.


        :param iata_code: The iata_code of this AirLineData.  # noqa: E501
        :type: str
        """

        self._iata_code = iata_code

    @property
    def iata_prefix_accounting(self):
        """Gets the iata_prefix_accounting of this AirLineData.  # noqa: E501


        :return: The iata_prefix_accounting of this AirLineData.  # noqa: E501
        :rtype: str
        """
        return self._iata_prefix_accounting

    @iata_prefix_accounting.setter
    def iata_prefix_accounting(self, iata_prefix_accounting):
        """Sets the iata_prefix_accounting of this AirLineData.


        :param iata_prefix_accounting: The iata_prefix_accounting of this AirLineData.  # noqa: E501
        :type: str
        """

        self._iata_prefix_accounting = iata_prefix_accounting

    @property
    def icao_code(self):
        """Gets the icao_code of this AirLineData.  # noqa: E501


        :return: The icao_code of this AirLineData.  # noqa: E501
        :rtype: str
        """
        return self._icao_code

    @icao_code.setter
    def icao_code(self, icao_code):
        """Sets the icao_code of this AirLineData.


        :param icao_code: The icao_code of this AirLineData.  # noqa: E501
        :type: str
        """

        self._icao_code = icao_code

    @property
    def callsign(self):
        """Gets the callsign of this AirLineData.  # noqa: E501


        :return: The callsign of this AirLineData.  # noqa: E501
        :rtype: str
        """
        return self._callsign

    @callsign.setter
    def callsign(self, callsign):
        """Sets the callsign of this AirLineData.


        :param callsign: The callsign of this AirLineData.  # noqa: E501
        :type: str
        """

        self._callsign = callsign

    @property
    def type(self):
        """Gets the type of this AirLineData.  # noqa: E501


        :return: The type of this AirLineData.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this AirLineData.


        :param type: The type of this AirLineData.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def status(self):
        """Gets the status of this AirLineData.  # noqa: E501


        :return: The status of this AirLineData.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this AirLineData.


        :param status: The status of this AirLineData.  # noqa: E501
        :type: str
        """

        self._status = status

    @property
    def fleet_size(self):
        """Gets the fleet_size of this AirLineData.  # noqa: E501


        :return: The fleet_size of this AirLineData.  # noqa: E501
        :rtype: str
        """
        return self._fleet_size

    @fleet_size.setter
    def fleet_size(self, fleet_size):
        """Sets the fleet_size of this AirLineData.


        :param fleet_size: The fleet_size of this AirLineData.  # noqa: E501
        :type: str
        """

        self._fleet_size = fleet_size

    @property
    def fleet_average_age(self):
        """Gets the fleet_average_age of this AirLineData.  # noqa: E501


        :return: The fleet_average_age of this AirLineData.  # noqa: E501
        :rtype: str
        """
        return self._fleet_average_age

    @fleet_average_age.setter
    def fleet_average_age(self, fleet_average_age):
        """Sets the fleet_average_age of this AirLineData.


        :param fleet_average_age: The fleet_average_age of this AirLineData.  # noqa: E501
        :type: str
        """

        self._fleet_average_age = fleet_average_age

    @property
    def date_founded(self):
        """Gets the date_founded of this AirLineData.  # noqa: E501


        :return: The date_founded of this AirLineData.  # noqa: E501
        :rtype: str
        """
        return self._date_founded

    @date_founded.setter
    def date_founded(self, date_founded):
        """Sets the date_founded of this AirLineData.


        :param date_founded: The date_founded of this AirLineData.  # noqa: E501
        :type: str
        """

        self._date_founded = date_founded

    @property
    def hub_code(self):
        """Gets the hub_code of this AirLineData.  # noqa: E501


        :return: The hub_code of this AirLineData.  # noqa: E501
        :rtype: str
        """
        return self._hub_code

    @hub_code.setter
    def hub_code(self, hub_code):
        """Sets the hub_code of this AirLineData.


        :param hub_code: The hub_code of this AirLineData.  # noqa: E501
        :type: str
        """

        self._hub_code = hub_code

    @property
    def country_name(self):
        """Gets the country_name of this AirLineData.  # noqa: E501


        :return: The country_name of this AirLineData.  # noqa: E501
        :rtype: str
        """
        return self._country_name

    @country_name.setter
    def country_name(self, country_name):
        """Sets the country_name of this AirLineData.


        :param country_name: The country_name of this AirLineData.  # noqa: E501
        :type: str
        """

        self._country_name = country_name

    @property
    def country_iso2(self):
        """Gets the country_iso2 of this AirLineData.  # noqa: E501


        :return: The country_iso2 of this AirLineData.  # noqa: E501
        :rtype: str
        """
        return self._country_iso2

    @country_iso2.setter
    def country_iso2(self, country_iso2):
        """Sets the country_iso2 of this AirLineData.


        :param country_iso2: The country_iso2 of this AirLineData.  # noqa: E501
        :type: str
        """

        self._country_iso2 = country_iso2

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AirLineData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AirLineData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
