# coding: utf-8

"""
    AviationStack

    The aviationstack API was built to provide a simple way of accessing global aviation data for real-time and historical flights as well as allow customers to tap into an extensive data set of airline routes and other up-to-date aviation-related information. Requests to the REST API are made using a straightforward HTTP GET URL structure and responses are provided in lightweight JSON format. The following API documentation can be applied for any major programming language and will present general integration guides and explanations around API endpoints, request parameters and response objects. If any questions remain unanswered for you, simply reach out to the aviationstack support team for assistance.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AirPlaneData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'airplane_id': 'str',
        'registration_number': 'str',
        'production_line': 'str',
        'iata_type': 'str',
        'model_name': 'str',
        'model_code': 'str',
        'icao_code_hex': 'str',
        'iata_code_short': 'str',
        'iata_code_long': 'str',
        'construction_number': 'str',
        'test_registration_number': 'str',
        'rollout_date': 'str',
        'first_flight_date': 'str',
        'delivery_date': 'str',
        'registration_date': 'str',
        'line_number': 'str',
        'plane_series': 'str',
        'airline_iata_code': 'str',
        'airline_icao_code': 'str',
        'plane_owner': 'str',
        'engines_count': 'str',
        'engines_type': 'str',
        'plane_age': 'str',
        'plane_status': 'str',
        'plane_class': 'str'
    }

    attribute_map = {
        'id': 'id',
        'airplane_id': 'airplane_id',
        'registration_number': 'registration_number',
        'production_line': 'production_line',
        'iata_type': 'iata_type',
        'model_name': 'model_name',
        'model_code': 'model_code',
        'icao_code_hex': 'icao_code_hex',
        'iata_code_short': 'iata_code_short',
        'iata_code_long': 'iata_code_long',
        'construction_number': 'construction_number',
        'test_registration_number': 'test_registration_number',
        'rollout_date': 'rollout_date',
        'first_flight_date': 'first_flight_date',
        'delivery_date': 'delivery_date',
        'registration_date': 'registration_date',
        'line_number': 'line_number',
        'plane_series': 'plane_series',
        'airline_iata_code': 'airline_iata_code',
        'airline_icao_code': 'airline_icao_code',
        'plane_owner': 'plane_owner',
        'engines_count': 'engines_count',
        'engines_type': 'engines_type',
        'plane_age': 'plane_age',
        'plane_status': 'plane_status',
        'plane_class': 'plane_class'
    }

    def __init__(self, id=None, airplane_id=None, registration_number=None, production_line=None, iata_type=None, model_name=None, model_code=None, icao_code_hex=None, iata_code_short=None, iata_code_long=None, construction_number=None, test_registration_number=None, rollout_date=None, first_flight_date=None, delivery_date=None, registration_date=None, line_number=None, plane_series=None, airline_iata_code=None, airline_icao_code=None, plane_owner=None, engines_count=None, engines_type=None, plane_age=None, plane_status=None, plane_class=None):  # noqa: E501
        """AirPlaneData - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._airplane_id = None
        self._registration_number = None
        self._production_line = None
        self._iata_type = None
        self._model_name = None
        self._model_code = None
        self._icao_code_hex = None
        self._iata_code_short = None
        self._iata_code_long = None
        self._construction_number = None
        self._test_registration_number = None
        self._rollout_date = None
        self._first_flight_date = None
        self._delivery_date = None
        self._registration_date = None
        self._line_number = None
        self._plane_series = None
        self._airline_iata_code = None
        self._airline_icao_code = None
        self._plane_owner = None
        self._engines_count = None
        self._engines_type = None
        self._plane_age = None
        self._plane_status = None
        self._plane_class = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if airplane_id is not None:
            self.airplane_id = airplane_id
        if registration_number is not None:
            self.registration_number = registration_number
        if production_line is not None:
            self.production_line = production_line
        if iata_type is not None:
            self.iata_type = iata_type
        if model_name is not None:
            self.model_name = model_name
        if model_code is not None:
            self.model_code = model_code
        if icao_code_hex is not None:
            self.icao_code_hex = icao_code_hex
        if iata_code_short is not None:
            self.iata_code_short = iata_code_short
        if iata_code_long is not None:
            self.iata_code_long = iata_code_long
        if construction_number is not None:
            self.construction_number = construction_number
        if test_registration_number is not None:
            self.test_registration_number = test_registration_number
        if rollout_date is not None:
            self.rollout_date = rollout_date
        if first_flight_date is not None:
            self.first_flight_date = first_flight_date
        if delivery_date is not None:
            self.delivery_date = delivery_date
        if registration_date is not None:
            self.registration_date = registration_date
        if line_number is not None:
            self.line_number = line_number
        if plane_series is not None:
            self.plane_series = plane_series
        if airline_iata_code is not None:
            self.airline_iata_code = airline_iata_code
        if airline_icao_code is not None:
            self.airline_icao_code = airline_icao_code
        if plane_owner is not None:
            self.plane_owner = plane_owner
        if engines_count is not None:
            self.engines_count = engines_count
        if engines_type is not None:
            self.engines_type = engines_type
        if plane_age is not None:
            self.plane_age = plane_age
        if plane_status is not None:
            self.plane_status = plane_status
        if plane_class is not None:
            self.plane_class = plane_class

    @property
    def id(self):
        """Gets the id of this AirPlaneData.  # noqa: E501


        :return: The id of this AirPlaneData.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this AirPlaneData.


        :param id: The id of this AirPlaneData.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def airplane_id(self):
        """Gets the airplane_id of this AirPlaneData.  # noqa: E501


        :return: The airplane_id of this AirPlaneData.  # noqa: E501
        :rtype: str
        """
        return self._airplane_id

    @airplane_id.setter
    def airplane_id(self, airplane_id):
        """Sets the airplane_id of this AirPlaneData.


        :param airplane_id: The airplane_id of this AirPlaneData.  # noqa: E501
        :type: str
        """

        self._airplane_id = airplane_id

    @property
    def registration_number(self):
        """Gets the registration_number of this AirPlaneData.  # noqa: E501


        :return: The registration_number of this AirPlaneData.  # noqa: E501
        :rtype: str
        """
        return self._registration_number

    @registration_number.setter
    def registration_number(self, registration_number):
        """Sets the registration_number of this AirPlaneData.


        :param registration_number: The registration_number of this AirPlaneData.  # noqa: E501
        :type: str
        """

        self._registration_number = registration_number

    @property
    def production_line(self):
        """Gets the production_line of this AirPlaneData.  # noqa: E501


        :return: The production_line of this AirPlaneData.  # noqa: E501
        :rtype: str
        """
        return self._production_line

    @production_line.setter
    def production_line(self, production_line):
        """Sets the production_line of this AirPlaneData.


        :param production_line: The production_line of this AirPlaneData.  # noqa: E501
        :type: str
        """

        self._production_line = production_line

    @property
    def iata_type(self):
        """Gets the iata_type of this AirPlaneData.  # noqa: E501


        :return: The iata_type of this AirPlaneData.  # noqa: E501
        :rtype: str
        """
        return self._iata_type

    @iata_type.setter
    def iata_type(self, iata_type):
        """Sets the iata_type of this AirPlaneData.


        :param iata_type: The iata_type of this AirPlaneData.  # noqa: E501
        :type: str
        """

        self._iata_type = iata_type

    @property
    def model_name(self):
        """Gets the model_name of this AirPlaneData.  # noqa: E501


        :return: The model_name of this AirPlaneData.  # noqa: E501
        :rtype: str
        """
        return self._model_name

    @model_name.setter
    def model_name(self, model_name):
        """Sets the model_name of this AirPlaneData.


        :param model_name: The model_name of this AirPlaneData.  # noqa: E501
        :type: str
        """

        self._model_name = model_name

    @property
    def model_code(self):
        """Gets the model_code of this AirPlaneData.  # noqa: E501


        :return: The model_code of this AirPlaneData.  # noqa: E501
        :rtype: str
        """
        return self._model_code

    @model_code.setter
    def model_code(self, model_code):
        """Sets the model_code of this AirPlaneData.


        :param model_code: The model_code of this AirPlaneData.  # noqa: E501
        :type: str
        """

        self._model_code = model_code

    @property
    def icao_code_hex(self):
        """Gets the icao_code_hex of this AirPlaneData.  # noqa: E501


        :return: The icao_code_hex of this AirPlaneData.  # noqa: E501
        :rtype: str
        """
        return self._icao_code_hex

    @icao_code_hex.setter
    def icao_code_hex(self, icao_code_hex):
        """Sets the icao_code_hex of this AirPlaneData.


        :param icao_code_hex: The icao_code_hex of this AirPlaneData.  # noqa: E501
        :type: str
        """

        self._icao_code_hex = icao_code_hex

    @property
    def iata_code_short(self):
        """Gets the iata_code_short of this AirPlaneData.  # noqa: E501


        :return: The iata_code_short of this AirPlaneData.  # noqa: E501
        :rtype: str
        """
        return self._iata_code_short

    @iata_code_short.setter
    def iata_code_short(self, iata_code_short):
        """Sets the iata_code_short of this AirPlaneData.


        :param iata_code_short: The iata_code_short of this AirPlaneData.  # noqa: E501
        :type: str
        """

        self._iata_code_short = iata_code_short

    @property
    def iata_code_long(self):
        """Gets the iata_code_long of this AirPlaneData.  # noqa: E501


        :return: The iata_code_long of this AirPlaneData.  # noqa: E501
        :rtype: str
        """
        return self._iata_code_long

    @iata_code_long.setter
    def iata_code_long(self, iata_code_long):
        """Sets the iata_code_long of this AirPlaneData.


        :param iata_code_long: The iata_code_long of this AirPlaneData.  # noqa: E501
        :type: str
        """

        self._iata_code_long = iata_code_long

    @property
    def construction_number(self):
        """Gets the construction_number of this AirPlaneData.  # noqa: E501


        :return: The construction_number of this AirPlaneData.  # noqa: E501
        :rtype: str
        """
        return self._construction_number

    @construction_number.setter
    def construction_number(self, construction_number):
        """Sets the construction_number of this AirPlaneData.


        :param construction_number: The construction_number of this AirPlaneData.  # noqa: E501
        :type: str
        """

        self._construction_number = construction_number

    @property
    def test_registration_number(self):
        """Gets the test_registration_number of this AirPlaneData.  # noqa: E501


        :return: The test_registration_number of this AirPlaneData.  # noqa: E501
        :rtype: str
        """
        return self._test_registration_number

    @test_registration_number.setter
    def test_registration_number(self, test_registration_number):
        """Sets the test_registration_number of this AirPlaneData.


        :param test_registration_number: The test_registration_number of this AirPlaneData.  # noqa: E501
        :type: str
        """

        self._test_registration_number = test_registration_number

    @property
    def rollout_date(self):
        """Gets the rollout_date of this AirPlaneData.  # noqa: E501


        :return: The rollout_date of this AirPlaneData.  # noqa: E501
        :rtype: str
        """
        return self._rollout_date

    @rollout_date.setter
    def rollout_date(self, rollout_date):
        """Sets the rollout_date of this AirPlaneData.


        :param rollout_date: The rollout_date of this AirPlaneData.  # noqa: E501
        :type: str
        """

        self._rollout_date = rollout_date

    @property
    def first_flight_date(self):
        """Gets the first_flight_date of this AirPlaneData.  # noqa: E501


        :return: The first_flight_date of this AirPlaneData.  # noqa: E501
        :rtype: str
        """
        return self._first_flight_date

    @first_flight_date.setter
    def first_flight_date(self, first_flight_date):
        """Sets the first_flight_date of this AirPlaneData.


        :param first_flight_date: The first_flight_date of this AirPlaneData.  # noqa: E501
        :type: str
        """

        self._first_flight_date = first_flight_date

    @property
    def delivery_date(self):
        """Gets the delivery_date of this AirPlaneData.  # noqa: E501


        :return: The delivery_date of this AirPlaneData.  # noqa: E501
        :rtype: str
        """
        return self._delivery_date

    @delivery_date.setter
    def delivery_date(self, delivery_date):
        """Sets the delivery_date of this AirPlaneData.


        :param delivery_date: The delivery_date of this AirPlaneData.  # noqa: E501
        :type: str
        """

        self._delivery_date = delivery_date

    @property
    def registration_date(self):
        """Gets the registration_date of this AirPlaneData.  # noqa: E501


        :return: The registration_date of this AirPlaneData.  # noqa: E501
        :rtype: str
        """
        return self._registration_date

    @registration_date.setter
    def registration_date(self, registration_date):
        """Sets the registration_date of this AirPlaneData.


        :param registration_date: The registration_date of this AirPlaneData.  # noqa: E501
        :type: str
        """

        self._registration_date = registration_date

    @property
    def line_number(self):
        """Gets the line_number of this AirPlaneData.  # noqa: E501


        :return: The line_number of this AirPlaneData.  # noqa: E501
        :rtype: str
        """
        return self._line_number

    @line_number.setter
    def line_number(self, line_number):
        """Sets the line_number of this AirPlaneData.


        :param line_number: The line_number of this AirPlaneData.  # noqa: E501
        :type: str
        """

        self._line_number = line_number

    @property
    def plane_series(self):
        """Gets the plane_series of this AirPlaneData.  # noqa: E501


        :return: The plane_series of this AirPlaneData.  # noqa: E501
        :rtype: str
        """
        return self._plane_series

    @plane_series.setter
    def plane_series(self, plane_series):
        """Sets the plane_series of this AirPlaneData.


        :param plane_series: The plane_series of this AirPlaneData.  # noqa: E501
        :type: str
        """

        self._plane_series = plane_series

    @property
    def airline_iata_code(self):
        """Gets the airline_iata_code of this AirPlaneData.  # noqa: E501


        :return: The airline_iata_code of this AirPlaneData.  # noqa: E501
        :rtype: str
        """
        return self._airline_iata_code

    @airline_iata_code.setter
    def airline_iata_code(self, airline_iata_code):
        """Sets the airline_iata_code of this AirPlaneData.


        :param airline_iata_code: The airline_iata_code of this AirPlaneData.  # noqa: E501
        :type: str
        """

        self._airline_iata_code = airline_iata_code

    @property
    def airline_icao_code(self):
        """Gets the airline_icao_code of this AirPlaneData.  # noqa: E501


        :return: The airline_icao_code of this AirPlaneData.  # noqa: E501
        :rtype: str
        """
        return self._airline_icao_code

    @airline_icao_code.setter
    def airline_icao_code(self, airline_icao_code):
        """Sets the airline_icao_code of this AirPlaneData.


        :param airline_icao_code: The airline_icao_code of this AirPlaneData.  # noqa: E501
        :type: str
        """

        self._airline_icao_code = airline_icao_code

    @property
    def plane_owner(self):
        """Gets the plane_owner of this AirPlaneData.  # noqa: E501


        :return: The plane_owner of this AirPlaneData.  # noqa: E501
        :rtype: str
        """
        return self._plane_owner

    @plane_owner.setter
    def plane_owner(self, plane_owner):
        """Sets the plane_owner of this AirPlaneData.


        :param plane_owner: The plane_owner of this AirPlaneData.  # noqa: E501
        :type: str
        """

        self._plane_owner = plane_owner

    @property
    def engines_count(self):
        """Gets the engines_count of this AirPlaneData.  # noqa: E501


        :return: The engines_count of this AirPlaneData.  # noqa: E501
        :rtype: str
        """
        return self._engines_count

    @engines_count.setter
    def engines_count(self, engines_count):
        """Sets the engines_count of this AirPlaneData.


        :param engines_count: The engines_count of this AirPlaneData.  # noqa: E501
        :type: str
        """

        self._engines_count = engines_count

    @property
    def engines_type(self):
        """Gets the engines_type of this AirPlaneData.  # noqa: E501


        :return: The engines_type of this AirPlaneData.  # noqa: E501
        :rtype: str
        """
        return self._engines_type

    @engines_type.setter
    def engines_type(self, engines_type):
        """Sets the engines_type of this AirPlaneData.


        :param engines_type: The engines_type of this AirPlaneData.  # noqa: E501
        :type: str
        """

        self._engines_type = engines_type

    @property
    def plane_age(self):
        """Gets the plane_age of this AirPlaneData.  # noqa: E501


        :return: The plane_age of this AirPlaneData.  # noqa: E501
        :rtype: str
        """
        return self._plane_age

    @plane_age.setter
    def plane_age(self, plane_age):
        """Sets the plane_age of this AirPlaneData.


        :param plane_age: The plane_age of this AirPlaneData.  # noqa: E501
        :type: str
        """

        self._plane_age = plane_age

    @property
    def plane_status(self):
        """Gets the plane_status of this AirPlaneData.  # noqa: E501


        :return: The plane_status of this AirPlaneData.  # noqa: E501
        :rtype: str
        """
        return self._plane_status

    @plane_status.setter
    def plane_status(self, plane_status):
        """Sets the plane_status of this AirPlaneData.


        :param plane_status: The plane_status of this AirPlaneData.  # noqa: E501
        :type: str
        """

        self._plane_status = plane_status

    @property
    def plane_class(self):
        """Gets the plane_class of this AirPlaneData.  # noqa: E501


        :return: The plane_class of this AirPlaneData.  # noqa: E501
        :rtype: str
        """
        return self._plane_class

    @plane_class.setter
    def plane_class(self, plane_class):
        """Sets the plane_class of this AirPlaneData.


        :param plane_class: The plane_class of this AirPlaneData.  # noqa: E501
        :type: str
        """

        self._plane_class = plane_class

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AirPlaneData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AirPlaneData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
