# coding: utf-8

"""
    AviationStack

    The aviationstack API was built to provide a simple way of accessing global aviation data for real-time and historical flights as well as allow customers to tap into an extensive data set of airline routes and other up-to-date aviation-related information. Requests to the REST API are made using a straightforward HTTP GET URL structure and responses are provided in lightweight JSON format. The following API documentation can be applied for any major programming language and will present general integration guides and explanations around API endpoints, request parameters and response objects. If any questions remain unanswered for you, simply reach out to the aviationstack support team for assistance.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AirCraftTypeData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'plane_type_id': 'str',
        'aircraft_name': 'str',
        'iata_code': 'str'
    }

    attribute_map = {
        'id': 'id',
        'plane_type_id': 'plane_type_id',
        'aircraft_name': 'aircraft_name',
        'iata_code': 'iata_code'
    }

    def __init__(self, id=None, plane_type_id=None, aircraft_name=None, iata_code=None):  # noqa: E501
        """AirCraftTypeData - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._plane_type_id = None
        self._aircraft_name = None
        self._iata_code = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if plane_type_id is not None:
            self.plane_type_id = plane_type_id
        if aircraft_name is not None:
            self.aircraft_name = aircraft_name
        if iata_code is not None:
            self.iata_code = iata_code

    @property
    def id(self):
        """Gets the id of this AirCraftTypeData.  # noqa: E501


        :return: The id of this AirCraftTypeData.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this AirCraftTypeData.


        :param id: The id of this AirCraftTypeData.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def plane_type_id(self):
        """Gets the plane_type_id of this AirCraftTypeData.  # noqa: E501


        :return: The plane_type_id of this AirCraftTypeData.  # noqa: E501
        :rtype: str
        """
        return self._plane_type_id

    @plane_type_id.setter
    def plane_type_id(self, plane_type_id):
        """Sets the plane_type_id of this AirCraftTypeData.


        :param plane_type_id: The plane_type_id of this AirCraftTypeData.  # noqa: E501
        :type: str
        """

        self._plane_type_id = plane_type_id

    @property
    def aircraft_name(self):
        """Gets the aircraft_name of this AirCraftTypeData.  # noqa: E501


        :return: The aircraft_name of this AirCraftTypeData.  # noqa: E501
        :rtype: str
        """
        return self._aircraft_name

    @aircraft_name.setter
    def aircraft_name(self, aircraft_name):
        """Sets the aircraft_name of this AirCraftTypeData.


        :param aircraft_name: The aircraft_name of this AirCraftTypeData.  # noqa: E501
        :type: str
        """

        self._aircraft_name = aircraft_name

    @property
    def iata_code(self):
        """Gets the iata_code of this AirCraftTypeData.  # noqa: E501


        :return: The iata_code of this AirCraftTypeData.  # noqa: E501
        :rtype: str
        """
        return self._iata_code

    @iata_code.setter
    def iata_code(self, iata_code):
        """Sets the iata_code of this AirCraftTypeData.


        :param iata_code: The iata_code of this AirCraftTypeData.  # noqa: E501
        :type: str
        """

        self._iata_code = iata_code

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AirCraftTypeData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AirCraftTypeData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
