# coding: utf-8

"""
    AviationStack

    The aviationstack API was built to provide a simple way of accessing global aviation data for real-time and historical flights as well as allow customers to tap into an extensive data set of airline routes and other up-to-date aviation-related information. Requests to the REST API are made using a straightforward HTTP GET URL structure and responses are provided in lightweight JSON format. The following API documentation can be applied for any major programming language and will present general integration guides and explanations around API endpoints, request parameters and response objects. If any questions remain unanswered for you, simply reach out to the aviationstack support team for assistance.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AirportData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'airport_id': 'str',
        'airport_name': 'str',
        'iata_code': 'str',
        'icao_code': 'str',
        'latitude': 'str',
        'longitude': 'str',
        'geoname_id': 'str',
        'timezone': 'str',
        'gmt': 'str',
        'phone_number': 'str',
        'country_name': 'str',
        'country_iso2': 'str',
        'city_iata_code': 'str'
    }

    attribute_map = {
        'id': 'id',
        'airport_id': 'airport_id',
        'airport_name': 'airport_name',
        'iata_code': 'iata_code',
        'icao_code': 'icao_code',
        'latitude': 'latitude',
        'longitude': 'longitude',
        'geoname_id': 'geoname_id',
        'timezone': 'timezone',
        'gmt': 'gmt',
        'phone_number': 'phone_number',
        'country_name': 'country_name',
        'country_iso2': 'country_iso2',
        'city_iata_code': 'city_iata_code'
    }

    def __init__(self, id=None, airport_id=None, airport_name=None, iata_code=None, icao_code=None, latitude=None, longitude=None, geoname_id=None, timezone=None, gmt=None, phone_number=None, country_name=None, country_iso2=None, city_iata_code=None):  # noqa: E501
        """AirportData - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._airport_id = None
        self._airport_name = None
        self._iata_code = None
        self._icao_code = None
        self._latitude = None
        self._longitude = None
        self._geoname_id = None
        self._timezone = None
        self._gmt = None
        self._phone_number = None
        self._country_name = None
        self._country_iso2 = None
        self._city_iata_code = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if airport_id is not None:
            self.airport_id = airport_id
        if airport_name is not None:
            self.airport_name = airport_name
        if iata_code is not None:
            self.iata_code = iata_code
        if icao_code is not None:
            self.icao_code = icao_code
        if latitude is not None:
            self.latitude = latitude
        if longitude is not None:
            self.longitude = longitude
        if geoname_id is not None:
            self.geoname_id = geoname_id
        if timezone is not None:
            self.timezone = timezone
        if gmt is not None:
            self.gmt = gmt
        if phone_number is not None:
            self.phone_number = phone_number
        if country_name is not None:
            self.country_name = country_name
        if country_iso2 is not None:
            self.country_iso2 = country_iso2
        if city_iata_code is not None:
            self.city_iata_code = city_iata_code

    @property
    def id(self):
        """Gets the id of this AirportData.  # noqa: E501


        :return: The id of this AirportData.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this AirportData.


        :param id: The id of this AirportData.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def airport_id(self):
        """Gets the airport_id of this AirportData.  # noqa: E501


        :return: The airport_id of this AirportData.  # noqa: E501
        :rtype: str
        """
        return self._airport_id

    @airport_id.setter
    def airport_id(self, airport_id):
        """Sets the airport_id of this AirportData.


        :param airport_id: The airport_id of this AirportData.  # noqa: E501
        :type: str
        """

        self._airport_id = airport_id

    @property
    def airport_name(self):
        """Gets the airport_name of this AirportData.  # noqa: E501


        :return: The airport_name of this AirportData.  # noqa: E501
        :rtype: str
        """
        return self._airport_name

    @airport_name.setter
    def airport_name(self, airport_name):
        """Sets the airport_name of this AirportData.


        :param airport_name: The airport_name of this AirportData.  # noqa: E501
        :type: str
        """

        self._airport_name = airport_name

    @property
    def iata_code(self):
        """Gets the iata_code of this AirportData.  # noqa: E501


        :return: The iata_code of this AirportData.  # noqa: E501
        :rtype: str
        """
        return self._iata_code

    @iata_code.setter
    def iata_code(self, iata_code):
        """Sets the iata_code of this AirportData.


        :param iata_code: The iata_code of this AirportData.  # noqa: E501
        :type: str
        """

        self._iata_code = iata_code

    @property
    def icao_code(self):
        """Gets the icao_code of this AirportData.  # noqa: E501


        :return: The icao_code of this AirportData.  # noqa: E501
        :rtype: str
        """
        return self._icao_code

    @icao_code.setter
    def icao_code(self, icao_code):
        """Sets the icao_code of this AirportData.


        :param icao_code: The icao_code of this AirportData.  # noqa: E501
        :type: str
        """

        self._icao_code = icao_code

    @property
    def latitude(self):
        """Gets the latitude of this AirportData.  # noqa: E501


        :return: The latitude of this AirportData.  # noqa: E501
        :rtype: str
        """
        return self._latitude

    @latitude.setter
    def latitude(self, latitude):
        """Sets the latitude of this AirportData.


        :param latitude: The latitude of this AirportData.  # noqa: E501
        :type: str
        """

        self._latitude = latitude

    @property
    def longitude(self):
        """Gets the longitude of this AirportData.  # noqa: E501


        :return: The longitude of this AirportData.  # noqa: E501
        :rtype: str
        """
        return self._longitude

    @longitude.setter
    def longitude(self, longitude):
        """Sets the longitude of this AirportData.


        :param longitude: The longitude of this AirportData.  # noqa: E501
        :type: str
        """

        self._longitude = longitude

    @property
    def geoname_id(self):
        """Gets the geoname_id of this AirportData.  # noqa: E501


        :return: The geoname_id of this AirportData.  # noqa: E501
        :rtype: str
        """
        return self._geoname_id

    @geoname_id.setter
    def geoname_id(self, geoname_id):
        """Sets the geoname_id of this AirportData.


        :param geoname_id: The geoname_id of this AirportData.  # noqa: E501
        :type: str
        """

        self._geoname_id = geoname_id

    @property
    def timezone(self):
        """Gets the timezone of this AirportData.  # noqa: E501


        :return: The timezone of this AirportData.  # noqa: E501
        :rtype: str
        """
        return self._timezone

    @timezone.setter
    def timezone(self, timezone):
        """Sets the timezone of this AirportData.


        :param timezone: The timezone of this AirportData.  # noqa: E501
        :type: str
        """

        self._timezone = timezone

    @property
    def gmt(self):
        """Gets the gmt of this AirportData.  # noqa: E501


        :return: The gmt of this AirportData.  # noqa: E501
        :rtype: str
        """
        return self._gmt

    @gmt.setter
    def gmt(self, gmt):
        """Sets the gmt of this AirportData.


        :param gmt: The gmt of this AirportData.  # noqa: E501
        :type: str
        """

        self._gmt = gmt

    @property
    def phone_number(self):
        """Gets the phone_number of this AirportData.  # noqa: E501


        :return: The phone_number of this AirportData.  # noqa: E501
        :rtype: str
        """
        return self._phone_number

    @phone_number.setter
    def phone_number(self, phone_number):
        """Sets the phone_number of this AirportData.


        :param phone_number: The phone_number of this AirportData.  # noqa: E501
        :type: str
        """

        self._phone_number = phone_number

    @property
    def country_name(self):
        """Gets the country_name of this AirportData.  # noqa: E501


        :return: The country_name of this AirportData.  # noqa: E501
        :rtype: str
        """
        return self._country_name

    @country_name.setter
    def country_name(self, country_name):
        """Sets the country_name of this AirportData.


        :param country_name: The country_name of this AirportData.  # noqa: E501
        :type: str
        """

        self._country_name = country_name

    @property
    def country_iso2(self):
        """Gets the country_iso2 of this AirportData.  # noqa: E501


        :return: The country_iso2 of this AirportData.  # noqa: E501
        :rtype: str
        """
        return self._country_iso2

    @country_iso2.setter
    def country_iso2(self, country_iso2):
        """Sets the country_iso2 of this AirportData.


        :param country_iso2: The country_iso2 of this AirportData.  # noqa: E501
        :type: str
        """

        self._country_iso2 = country_iso2

    @property
    def city_iata_code(self):
        """Gets the city_iata_code of this AirportData.  # noqa: E501


        :return: The city_iata_code of this AirportData.  # noqa: E501
        :rtype: str
        """
        return self._city_iata_code

    @city_iata_code.setter
    def city_iata_code(self, city_iata_code):
        """Sets the city_iata_code of this AirportData.


        :param city_iata_code: The city_iata_code of this AirportData.  # noqa: E501
        :type: str
        """

        self._city_iata_code = city_iata_code

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AirportData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AirportData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
