# coding: utf-8

"""
    AviationStack

    The aviationstack API was built to provide a simple way of accessing global aviation data for real-time and historical flights as well as allow customers to tap into an extensive data set of airline routes and other up-to-date aviation-related information. Requests to the REST API are made using a straightforward HTTP GET URL structure and responses are provided in lightweight JSON format. The following API documentation can be applied for any major programming language and will present general integration guides and explanations around API endpoints, request parameters and response objects. If any questions remain unanswered for you, simply reach out to the aviationstack support team for assistance.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CityData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'city_id': 'str',
        'city_name': 'str',
        'iata_code': 'str',
        'country_iso2': 'str',
        'latitude': 'str',
        'longitude': 'str',
        'timezone': 'str',
        'gmt': 'str',
        'geoname_id': 'str'
    }

    attribute_map = {
        'id': 'id',
        'city_id': 'city_id',
        'city_name': 'city_name',
        'iata_code': 'iata_code',
        'country_iso2': 'country_iso2',
        'latitude': 'latitude',
        'longitude': 'longitude',
        'timezone': 'timezone',
        'gmt': 'gmt',
        'geoname_id': 'geoname_id'
    }

    def __init__(self, id=None, city_id=None, city_name=None, iata_code=None, country_iso2=None, latitude=None, longitude=None, timezone=None, gmt=None, geoname_id=None):  # noqa: E501
        """CityData - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._city_id = None
        self._city_name = None
        self._iata_code = None
        self._country_iso2 = None
        self._latitude = None
        self._longitude = None
        self._timezone = None
        self._gmt = None
        self._geoname_id = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if city_id is not None:
            self.city_id = city_id
        if city_name is not None:
            self.city_name = city_name
        if iata_code is not None:
            self.iata_code = iata_code
        if country_iso2 is not None:
            self.country_iso2 = country_iso2
        if latitude is not None:
            self.latitude = latitude
        if longitude is not None:
            self.longitude = longitude
        if timezone is not None:
            self.timezone = timezone
        if gmt is not None:
            self.gmt = gmt
        if geoname_id is not None:
            self.geoname_id = geoname_id

    @property
    def id(self):
        """Gets the id of this CityData.  # noqa: E501


        :return: The id of this CityData.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this CityData.


        :param id: The id of this CityData.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def city_id(self):
        """Gets the city_id of this CityData.  # noqa: E501


        :return: The city_id of this CityData.  # noqa: E501
        :rtype: str
        """
        return self._city_id

    @city_id.setter
    def city_id(self, city_id):
        """Sets the city_id of this CityData.


        :param city_id: The city_id of this CityData.  # noqa: E501
        :type: str
        """

        self._city_id = city_id

    @property
    def city_name(self):
        """Gets the city_name of this CityData.  # noqa: E501


        :return: The city_name of this CityData.  # noqa: E501
        :rtype: str
        """
        return self._city_name

    @city_name.setter
    def city_name(self, city_name):
        """Sets the city_name of this CityData.


        :param city_name: The city_name of this CityData.  # noqa: E501
        :type: str
        """

        self._city_name = city_name

    @property
    def iata_code(self):
        """Gets the iata_code of this CityData.  # noqa: E501


        :return: The iata_code of this CityData.  # noqa: E501
        :rtype: str
        """
        return self._iata_code

    @iata_code.setter
    def iata_code(self, iata_code):
        """Sets the iata_code of this CityData.


        :param iata_code: The iata_code of this CityData.  # noqa: E501
        :type: str
        """

        self._iata_code = iata_code

    @property
    def country_iso2(self):
        """Gets the country_iso2 of this CityData.  # noqa: E501


        :return: The country_iso2 of this CityData.  # noqa: E501
        :rtype: str
        """
        return self._country_iso2

    @country_iso2.setter
    def country_iso2(self, country_iso2):
        """Sets the country_iso2 of this CityData.


        :param country_iso2: The country_iso2 of this CityData.  # noqa: E501
        :type: str
        """

        self._country_iso2 = country_iso2

    @property
    def latitude(self):
        """Gets the latitude of this CityData.  # noqa: E501


        :return: The latitude of this CityData.  # noqa: E501
        :rtype: str
        """
        return self._latitude

    @latitude.setter
    def latitude(self, latitude):
        """Sets the latitude of this CityData.


        :param latitude: The latitude of this CityData.  # noqa: E501
        :type: str
        """

        self._latitude = latitude

    @property
    def longitude(self):
        """Gets the longitude of this CityData.  # noqa: E501


        :return: The longitude of this CityData.  # noqa: E501
        :rtype: str
        """
        return self._longitude

    @longitude.setter
    def longitude(self, longitude):
        """Sets the longitude of this CityData.


        :param longitude: The longitude of this CityData.  # noqa: E501
        :type: str
        """

        self._longitude = longitude

    @property
    def timezone(self):
        """Gets the timezone of this CityData.  # noqa: E501


        :return: The timezone of this CityData.  # noqa: E501
        :rtype: str
        """
        return self._timezone

    @timezone.setter
    def timezone(self, timezone):
        """Sets the timezone of this CityData.


        :param timezone: The timezone of this CityData.  # noqa: E501
        :type: str
        """

        self._timezone = timezone

    @property
    def gmt(self):
        """Gets the gmt of this CityData.  # noqa: E501


        :return: The gmt of this CityData.  # noqa: E501
        :rtype: str
        """
        return self._gmt

    @gmt.setter
    def gmt(self, gmt):
        """Sets the gmt of this CityData.


        :param gmt: The gmt of this CityData.  # noqa: E501
        :type: str
        """

        self._gmt = gmt

    @property
    def geoname_id(self):
        """Gets the geoname_id of this CityData.  # noqa: E501


        :return: The geoname_id of this CityData.  # noqa: E501
        :rtype: str
        """
        return self._geoname_id

    @geoname_id.setter
    def geoname_id(self, geoname_id):
        """Sets the geoname_id of this CityData.


        :param geoname_id: The geoname_id of this CityData.  # noqa: E501
        :type: str
        """

        self._geoname_id = geoname_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CityData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CityData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
