# coding: utf-8

"""
    AviationStack

    The aviationstack API was built to provide a simple way of accessing global aviation data for real-time and historical flights as well as allow customers to tap into an extensive data set of airline routes and other up-to-date aviation-related information. Requests to the REST API are made using a straightforward HTTP GET URL structure and responses are provided in lightweight JSON format. The following API documentation can be applied for any major programming language and will present general integration guides and explanations around API endpoints, request parameters and response objects. If any questions remain unanswered for you, simply reach out to the aviationstack support team for assistance.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CountryData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'country_id': 'str',
        'country_name': 'str',
        'country_iso2': 'str',
        'country_iso3': 'str',
        'country_iso_numeric': 'str',
        'population': 'str',
        'capital': 'str',
        'continent': 'str',
        'currency_name': 'str',
        'currency_code': 'str',
        'fips_code': 'str',
        'phone_prefix': 'str'
    }

    attribute_map = {
        'id': 'id',
        'country_id': 'country_id',
        'country_name': 'country_name',
        'country_iso2': 'country_iso2',
        'country_iso3': 'country_iso3',
        'country_iso_numeric': 'country_iso_numeric',
        'population': 'population',
        'capital': 'capital',
        'continent': 'continent',
        'currency_name': 'currency_name',
        'currency_code': 'currency_code',
        'fips_code': 'fips_code',
        'phone_prefix': 'phone_prefix'
    }

    def __init__(self, id=None, country_id=None, country_name=None, country_iso2=None, country_iso3=None, country_iso_numeric=None, population=None, capital=None, continent=None, currency_name=None, currency_code=None, fips_code=None, phone_prefix=None):  # noqa: E501
        """CountryData - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._country_id = None
        self._country_name = None
        self._country_iso2 = None
        self._country_iso3 = None
        self._country_iso_numeric = None
        self._population = None
        self._capital = None
        self._continent = None
        self._currency_name = None
        self._currency_code = None
        self._fips_code = None
        self._phone_prefix = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if country_id is not None:
            self.country_id = country_id
        if country_name is not None:
            self.country_name = country_name
        if country_iso2 is not None:
            self.country_iso2 = country_iso2
        if country_iso3 is not None:
            self.country_iso3 = country_iso3
        if country_iso_numeric is not None:
            self.country_iso_numeric = country_iso_numeric
        if population is not None:
            self.population = population
        if capital is not None:
            self.capital = capital
        if continent is not None:
            self.continent = continent
        if currency_name is not None:
            self.currency_name = currency_name
        if currency_code is not None:
            self.currency_code = currency_code
        if fips_code is not None:
            self.fips_code = fips_code
        if phone_prefix is not None:
            self.phone_prefix = phone_prefix

    @property
    def id(self):
        """Gets the id of this CountryData.  # noqa: E501


        :return: The id of this CountryData.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this CountryData.


        :param id: The id of this CountryData.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def country_id(self):
        """Gets the country_id of this CountryData.  # noqa: E501


        :return: The country_id of this CountryData.  # noqa: E501
        :rtype: str
        """
        return self._country_id

    @country_id.setter
    def country_id(self, country_id):
        """Sets the country_id of this CountryData.


        :param country_id: The country_id of this CountryData.  # noqa: E501
        :type: str
        """

        self._country_id = country_id

    @property
    def country_name(self):
        """Gets the country_name of this CountryData.  # noqa: E501


        :return: The country_name of this CountryData.  # noqa: E501
        :rtype: str
        """
        return self._country_name

    @country_name.setter
    def country_name(self, country_name):
        """Sets the country_name of this CountryData.


        :param country_name: The country_name of this CountryData.  # noqa: E501
        :type: str
        """

        self._country_name = country_name

    @property
    def country_iso2(self):
        """Gets the country_iso2 of this CountryData.  # noqa: E501


        :return: The country_iso2 of this CountryData.  # noqa: E501
        :rtype: str
        """
        return self._country_iso2

    @country_iso2.setter
    def country_iso2(self, country_iso2):
        """Sets the country_iso2 of this CountryData.


        :param country_iso2: The country_iso2 of this CountryData.  # noqa: E501
        :type: str
        """

        self._country_iso2 = country_iso2

    @property
    def country_iso3(self):
        """Gets the country_iso3 of this CountryData.  # noqa: E501


        :return: The country_iso3 of this CountryData.  # noqa: E501
        :rtype: str
        """
        return self._country_iso3

    @country_iso3.setter
    def country_iso3(self, country_iso3):
        """Sets the country_iso3 of this CountryData.


        :param country_iso3: The country_iso3 of this CountryData.  # noqa: E501
        :type: str
        """

        self._country_iso3 = country_iso3

    @property
    def country_iso_numeric(self):
        """Gets the country_iso_numeric of this CountryData.  # noqa: E501


        :return: The country_iso_numeric of this CountryData.  # noqa: E501
        :rtype: str
        """
        return self._country_iso_numeric

    @country_iso_numeric.setter
    def country_iso_numeric(self, country_iso_numeric):
        """Sets the country_iso_numeric of this CountryData.


        :param country_iso_numeric: The country_iso_numeric of this CountryData.  # noqa: E501
        :type: str
        """

        self._country_iso_numeric = country_iso_numeric

    @property
    def population(self):
        """Gets the population of this CountryData.  # noqa: E501


        :return: The population of this CountryData.  # noqa: E501
        :rtype: str
        """
        return self._population

    @population.setter
    def population(self, population):
        """Sets the population of this CountryData.


        :param population: The population of this CountryData.  # noqa: E501
        :type: str
        """

        self._population = population

    @property
    def capital(self):
        """Gets the capital of this CountryData.  # noqa: E501


        :return: The capital of this CountryData.  # noqa: E501
        :rtype: str
        """
        return self._capital

    @capital.setter
    def capital(self, capital):
        """Sets the capital of this CountryData.


        :param capital: The capital of this CountryData.  # noqa: E501
        :type: str
        """

        self._capital = capital

    @property
    def continent(self):
        """Gets the continent of this CountryData.  # noqa: E501


        :return: The continent of this CountryData.  # noqa: E501
        :rtype: str
        """
        return self._continent

    @continent.setter
    def continent(self, continent):
        """Sets the continent of this CountryData.


        :param continent: The continent of this CountryData.  # noqa: E501
        :type: str
        """

        self._continent = continent

    @property
    def currency_name(self):
        """Gets the currency_name of this CountryData.  # noqa: E501


        :return: The currency_name of this CountryData.  # noqa: E501
        :rtype: str
        """
        return self._currency_name

    @currency_name.setter
    def currency_name(self, currency_name):
        """Sets the currency_name of this CountryData.


        :param currency_name: The currency_name of this CountryData.  # noqa: E501
        :type: str
        """

        self._currency_name = currency_name

    @property
    def currency_code(self):
        """Gets the currency_code of this CountryData.  # noqa: E501


        :return: The currency_code of this CountryData.  # noqa: E501
        :rtype: str
        """
        return self._currency_code

    @currency_code.setter
    def currency_code(self, currency_code):
        """Sets the currency_code of this CountryData.


        :param currency_code: The currency_code of this CountryData.  # noqa: E501
        :type: str
        """

        self._currency_code = currency_code

    @property
    def fips_code(self):
        """Gets the fips_code of this CountryData.  # noqa: E501


        :return: The fips_code of this CountryData.  # noqa: E501
        :rtype: str
        """
        return self._fips_code

    @fips_code.setter
    def fips_code(self, fips_code):
        """Sets the fips_code of this CountryData.


        :param fips_code: The fips_code of this CountryData.  # noqa: E501
        :type: str
        """

        self._fips_code = fips_code

    @property
    def phone_prefix(self):
        """Gets the phone_prefix of this CountryData.  # noqa: E501


        :return: The phone_prefix of this CountryData.  # noqa: E501
        :rtype: str
        """
        return self._phone_prefix

    @phone_prefix.setter
    def phone_prefix(self, phone_prefix):
        """Sets the phone_prefix of this CountryData.


        :param phone_prefix: The phone_prefix of this CountryData.  # noqa: E501
        :type: str
        """

        self._phone_prefix = phone_prefix

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CountryData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CountryData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
