# coding: utf-8

"""
    AviationStack

    The aviationstack API was built to provide a simple way of accessing global aviation data for real-time and historical flights as well as allow customers to tap into an extensive data set of airline routes and other up-to-date aviation-related information. Requests to the REST API are made using a straightforward HTTP GET URL structure and responses are provided in lightweight JSON format. The following API documentation can be applied for any major programming language and will present general integration guides and explanations around API endpoints, request parameters and response objects. If any questions remain unanswered for you, simply reach out to the aviationstack support team for assistance.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DataFlight(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'flight_date': 'str',
        'flight_status': 'str',
        'departure': 'DataDeparture',
        'arrival': 'DataDeparture',
        'airline': 'DataAirline',
        'flight': 'DataFlight2',
        'aircraft': 'DataAircraft',
        'live': 'Datalive'
    }

    attribute_map = {
        'flight_date': 'flight_date',
        'flight_status': 'flight_status',
        'departure': 'departure',
        'arrival': 'arrival',
        'airline': 'airline',
        'flight': 'flight',
        'aircraft': 'aircraft',
        'live': 'live'
    }

    def __init__(self, flight_date=None, flight_status=None, departure=None, arrival=None, airline=None, flight=None, aircraft=None, live=None):  # noqa: E501
        """DataFlight - a model defined in Swagger"""  # noqa: E501
        self._flight_date = None
        self._flight_status = None
        self._departure = None
        self._arrival = None
        self._airline = None
        self._flight = None
        self._aircraft = None
        self._live = None
        self.discriminator = None
        if flight_date is not None:
            self.flight_date = flight_date
        if flight_status is not None:
            self.flight_status = flight_status
        if departure is not None:
            self.departure = departure
        if arrival is not None:
            self.arrival = arrival
        if airline is not None:
            self.airline = airline
        if flight is not None:
            self.flight = flight
        if aircraft is not None:
            self.aircraft = aircraft
        if live is not None:
            self.live = live

    @property
    def flight_date(self):
        """Gets the flight_date of this DataFlight.  # noqa: E501


        :return: The flight_date of this DataFlight.  # noqa: E501
        :rtype: str
        """
        return self._flight_date

    @flight_date.setter
    def flight_date(self, flight_date):
        """Sets the flight_date of this DataFlight.


        :param flight_date: The flight_date of this DataFlight.  # noqa: E501
        :type: str
        """

        self._flight_date = flight_date

    @property
    def flight_status(self):
        """Gets the flight_status of this DataFlight.  # noqa: E501


        :return: The flight_status of this DataFlight.  # noqa: E501
        :rtype: str
        """
        return self._flight_status

    @flight_status.setter
    def flight_status(self, flight_status):
        """Sets the flight_status of this DataFlight.


        :param flight_status: The flight_status of this DataFlight.  # noqa: E501
        :type: str
        """

        self._flight_status = flight_status

    @property
    def departure(self):
        """Gets the departure of this DataFlight.  # noqa: E501


        :return: The departure of this DataFlight.  # noqa: E501
        :rtype: DataDeparture
        """
        return self._departure

    @departure.setter
    def departure(self, departure):
        """Sets the departure of this DataFlight.


        :param departure: The departure of this DataFlight.  # noqa: E501
        :type: DataDeparture
        """

        self._departure = departure

    @property
    def arrival(self):
        """Gets the arrival of this DataFlight.  # noqa: E501


        :return: The arrival of this DataFlight.  # noqa: E501
        :rtype: DataDeparture
        """
        return self._arrival

    @arrival.setter
    def arrival(self, arrival):
        """Sets the arrival of this DataFlight.


        :param arrival: The arrival of this DataFlight.  # noqa: E501
        :type: DataDeparture
        """

        self._arrival = arrival

    @property
    def airline(self):
        """Gets the airline of this DataFlight.  # noqa: E501


        :return: The airline of this DataFlight.  # noqa: E501
        :rtype: DataAirline
        """
        return self._airline

    @airline.setter
    def airline(self, airline):
        """Sets the airline of this DataFlight.


        :param airline: The airline of this DataFlight.  # noqa: E501
        :type: DataAirline
        """

        self._airline = airline

    @property
    def flight(self):
        """Gets the flight of this DataFlight.  # noqa: E501


        :return: The flight of this DataFlight.  # noqa: E501
        :rtype: DataFlight2
        """
        return self._flight

    @flight.setter
    def flight(self, flight):
        """Sets the flight of this DataFlight.


        :param flight: The flight of this DataFlight.  # noqa: E501
        :type: DataFlight2
        """

        self._flight = flight

    @property
    def aircraft(self):
        """Gets the aircraft of this DataFlight.  # noqa: E501


        :return: The aircraft of this DataFlight.  # noqa: E501
        :rtype: DataAircraft
        """
        return self._aircraft

    @aircraft.setter
    def aircraft(self, aircraft):
        """Sets the aircraft of this DataFlight.


        :param aircraft: The aircraft of this DataFlight.  # noqa: E501
        :type: DataAircraft
        """

        self._aircraft = aircraft

    @property
    def live(self):
        """Gets the live of this DataFlight.  # noqa: E501


        :return: The live of this DataFlight.  # noqa: E501
        :rtype: Datalive
        """
        return self._live

    @live.setter
    def live(self, live):
        """Sets the live of this DataFlight.


        :param live: The live of this DataFlight.  # noqa: E501
        :type: Datalive
        """

        self._live = live

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DataFlight, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DataFlight):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
