# coding: utf-8

"""
    AviationStack

    The aviationstack API was built to provide a simple way of accessing global aviation data for real-time and historical flights as well as allow customers to tap into an extensive data set of airline routes and other up-to-date aviation-related information. Requests to the REST API are made using a straightforward HTTP GET URL structure and responses are provided in lightweight JSON format. The following API documentation can be applied for any major programming language and will present general integration guides and explanations around API endpoints, request parameters and response objects. If any questions remain unanswered for you, simply reach out to the aviationstack support team for assistance.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DataRoutes(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'departure': 'RouteEndpoint',
        'arrival': 'RouteEndpoint',
        'airline': 'RouteAirline',
        'flight': 'DataRoutesFlight'
    }

    attribute_map = {
        'departure': 'departure',
        'arrival': 'arrival',
        'airline': 'airline',
        'flight': 'flight'
    }

    def __init__(self, departure=None, arrival=None, airline=None, flight=None):  # noqa: E501
        """DataRoutes - a model defined in Swagger"""  # noqa: E501
        self._departure = None
        self._arrival = None
        self._airline = None
        self._flight = None
        self.discriminator = None
        if departure is not None:
            self.departure = departure
        if arrival is not None:
            self.arrival = arrival
        if airline is not None:
            self.airline = airline
        if flight is not None:
            self.flight = flight

    @property
    def departure(self):
        """Gets the departure of this DataRoutes.  # noqa: E501


        :return: The departure of this DataRoutes.  # noqa: E501
        :rtype: RouteEndpoint
        """
        return self._departure

    @departure.setter
    def departure(self, departure):
        """Sets the departure of this DataRoutes.


        :param departure: The departure of this DataRoutes.  # noqa: E501
        :type: RouteEndpoint
        """

        self._departure = departure

    @property
    def arrival(self):
        """Gets the arrival of this DataRoutes.  # noqa: E501


        :return: The arrival of this DataRoutes.  # noqa: E501
        :rtype: RouteEndpoint
        """
        return self._arrival

    @arrival.setter
    def arrival(self, arrival):
        """Sets the arrival of this DataRoutes.


        :param arrival: The arrival of this DataRoutes.  # noqa: E501
        :type: RouteEndpoint
        """

        self._arrival = arrival

    @property
    def airline(self):
        """Gets the airline of this DataRoutes.  # noqa: E501


        :return: The airline of this DataRoutes.  # noqa: E501
        :rtype: RouteAirline
        """
        return self._airline

    @airline.setter
    def airline(self, airline):
        """Sets the airline of this DataRoutes.


        :param airline: The airline of this DataRoutes.  # noqa: E501
        :type: RouteAirline
        """

        self._airline = airline

    @property
    def flight(self):
        """Gets the flight of this DataRoutes.  # noqa: E501


        :return: The flight of this DataRoutes.  # noqa: E501
        :rtype: DataRoutesFlight
        """
        return self._flight

    @flight.setter
    def flight(self, flight):
        """Sets the flight of this DataRoutes.


        :param flight: The flight of this DataRoutes.  # noqa: E501
        :type: DataRoutesFlight
        """

        self._flight = flight

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DataRoutes, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DataRoutes):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
