# coding: utf-8

"""
    AviationStack

    The aviationstack API was built to provide a simple way of accessing global aviation data for real-time and historical flights as well as allow customers to tap into an extensive data set of airline routes and other up-to-date aviation-related information. Requests to the REST API are made using a straightforward HTTP GET URL structure and responses are provided in lightweight JSON format. The following API documentation can be applied for any major programming language and will present general integration guides and explanations around API endpoints, request parameters and response objects. If any questions remain unanswered for you, simply reach out to the aviationstack support team for assistance.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DataDeparture(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'airport': 'str',
        'timezone': 'str',
        'iata': 'str',
        'icao': 'str',
        'terminal': 'str',
        'gate': 'str',
        'delay': 'int',
        'scheduled': 'str',
        'estimated': 'str',
        'actual': 'str',
        'estimated_runway': 'str',
        'actual_runway': 'str',
        'baggage': 'str'
    }

    attribute_map = {
        'airport': 'airport',
        'timezone': 'timezone',
        'iata': 'iata',
        'icao': 'icao',
        'terminal': 'terminal',
        'gate': 'gate',
        'delay': 'delay',
        'scheduled': 'scheduled',
        'estimated': 'estimated',
        'actual': 'actual',
        'estimated_runway': 'estimated_runway',
        'actual_runway': 'actual_runway',
        'baggage': 'baggage'
    }

    def __init__(self, airport=None, timezone=None, iata=None, icao=None, terminal=None, gate=None, delay=None, scheduled=None, estimated=None, actual=None, estimated_runway=None, actual_runway=None, baggage=None):  # noqa: E501
        """DataDeparture - a model defined in Swagger"""  # noqa: E501
        self._airport = None
        self._timezone = None
        self._iata = None
        self._icao = None
        self._terminal = None
        self._gate = None
        self._delay = None
        self._scheduled = None
        self._estimated = None
        self._actual = None
        self._estimated_runway = None
        self._actual_runway = None
        self._baggage = None
        self.discriminator = None
        if airport is not None:
            self.airport = airport
        if timezone is not None:
            self.timezone = timezone
        if iata is not None:
            self.iata = iata
        if icao is not None:
            self.icao = icao
        if terminal is not None:
            self.terminal = terminal
        if gate is not None:
            self.gate = gate
        if delay is not None:
            self.delay = delay
        if scheduled is not None:
            self.scheduled = scheduled
        if estimated is not None:
            self.estimated = estimated
        if actual is not None:
            self.actual = actual
        if estimated_runway is not None:
            self.estimated_runway = estimated_runway
        if actual_runway is not None:
            self.actual_runway = actual_runway
        if baggage is not None:
            self.baggage = baggage

    @property
    def airport(self):
        """Gets the airport of this DataDeparture.  # noqa: E501


        :return: The airport of this DataDeparture.  # noqa: E501
        :rtype: str
        """
        return self._airport

    @airport.setter
    def airport(self, airport):
        """Sets the airport of this DataDeparture.


        :param airport: The airport of this DataDeparture.  # noqa: E501
        :type: str
        """

        self._airport = airport

    @property
    def timezone(self):
        """Gets the timezone of this DataDeparture.  # noqa: E501


        :return: The timezone of this DataDeparture.  # noqa: E501
        :rtype: str
        """
        return self._timezone

    @timezone.setter
    def timezone(self, timezone):
        """Sets the timezone of this DataDeparture.


        :param timezone: The timezone of this DataDeparture.  # noqa: E501
        :type: str
        """

        self._timezone = timezone

    @property
    def iata(self):
        """Gets the iata of this DataDeparture.  # noqa: E501


        :return: The iata of this DataDeparture.  # noqa: E501
        :rtype: str
        """
        return self._iata

    @iata.setter
    def iata(self, iata):
        """Sets the iata of this DataDeparture.


        :param iata: The iata of this DataDeparture.  # noqa: E501
        :type: str
        """

        self._iata = iata

    @property
    def icao(self):
        """Gets the icao of this DataDeparture.  # noqa: E501


        :return: The icao of this DataDeparture.  # noqa: E501
        :rtype: str
        """
        return self._icao

    @icao.setter
    def icao(self, icao):
        """Sets the icao of this DataDeparture.


        :param icao: The icao of this DataDeparture.  # noqa: E501
        :type: str
        """

        self._icao = icao

    @property
    def terminal(self):
        """Gets the terminal of this DataDeparture.  # noqa: E501


        :return: The terminal of this DataDeparture.  # noqa: E501
        :rtype: str
        """
        return self._terminal

    @terminal.setter
    def terminal(self, terminal):
        """Sets the terminal of this DataDeparture.


        :param terminal: The terminal of this DataDeparture.  # noqa: E501
        :type: str
        """

        self._terminal = terminal

    @property
    def gate(self):
        """Gets the gate of this DataDeparture.  # noqa: E501


        :return: The gate of this DataDeparture.  # noqa: E501
        :rtype: str
        """
        return self._gate

    @gate.setter
    def gate(self, gate):
        """Sets the gate of this DataDeparture.


        :param gate: The gate of this DataDeparture.  # noqa: E501
        :type: str
        """

        self._gate = gate

    @property
    def delay(self):
        """Gets the delay of this DataDeparture.  # noqa: E501


        :return: The delay of this DataDeparture.  # noqa: E501
        :rtype: int
        """
        return self._delay

    @delay.setter
    def delay(self, delay):
        """Sets the delay of this DataDeparture.


        :param delay: The delay of this DataDeparture.  # noqa: E501
        :type: int
        """

        self._delay = delay

    @property
    def scheduled(self):
        """Gets the scheduled of this DataDeparture.  # noqa: E501


        :return: The scheduled of this DataDeparture.  # noqa: E501
        :rtype: str
        """
        return self._scheduled

    @scheduled.setter
    def scheduled(self, scheduled):
        """Sets the scheduled of this DataDeparture.


        :param scheduled: The scheduled of this DataDeparture.  # noqa: E501
        :type: str
        """

        self._scheduled = scheduled

    @property
    def estimated(self):
        """Gets the estimated of this DataDeparture.  # noqa: E501


        :return: The estimated of this DataDeparture.  # noqa: E501
        :rtype: str
        """
        return self._estimated

    @estimated.setter
    def estimated(self, estimated):
        """Sets the estimated of this DataDeparture.


        :param estimated: The estimated of this DataDeparture.  # noqa: E501
        :type: str
        """

        self._estimated = estimated

    @property
    def actual(self):
        """Gets the actual of this DataDeparture.  # noqa: E501


        :return: The actual of this DataDeparture.  # noqa: E501
        :rtype: str
        """
        return self._actual

    @actual.setter
    def actual(self, actual):
        """Sets the actual of this DataDeparture.


        :param actual: The actual of this DataDeparture.  # noqa: E501
        :type: str
        """

        self._actual = actual

    @property
    def estimated_runway(self):
        """Gets the estimated_runway of this DataDeparture.  # noqa: E501


        :return: The estimated_runway of this DataDeparture.  # noqa: E501
        :rtype: str
        """
        return self._estimated_runway

    @estimated_runway.setter
    def estimated_runway(self, estimated_runway):
        """Sets the estimated_runway of this DataDeparture.


        :param estimated_runway: The estimated_runway of this DataDeparture.  # noqa: E501
        :type: str
        """

        self._estimated_runway = estimated_runway

    @property
    def actual_runway(self):
        """Gets the actual_runway of this DataDeparture.  # noqa: E501


        :return: The actual_runway of this DataDeparture.  # noqa: E501
        :rtype: str
        """
        return self._actual_runway

    @actual_runway.setter
    def actual_runway(self, actual_runway):
        """Sets the actual_runway of this DataDeparture.


        :param actual_runway: The actual_runway of this DataDeparture.  # noqa: E501
        :type: str
        """

        self._actual_runway = actual_runway

    @property
    def baggage(self):
        """Gets the baggage of this DataDeparture.  # noqa: E501


        :return: The baggage of this DataDeparture.  # noqa: E501
        :rtype: str
        """
        return self._baggage

    @baggage.setter
    def baggage(self, baggage):
        """Sets the baggage of this DataDeparture.


        :param baggage: The baggage of this DataDeparture.  # noqa: E501
        :type: str
        """

        self._baggage = baggage

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DataDeparture, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DataDeparture):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
