# coding: utf-8

"""
    AviationStack

    The aviationstack API was built to provide a simple way of accessing global aviation data for real-time and historical flights as well as allow customers to tap into an extensive data set of airline routes and other up-to-date aviation-related information. Requests to the REST API are made using a straightforward HTTP GET URL structure and responses are provided in lightweight JSON format. The following API documentation can be applied for any major programming language and will present general integration guides and explanations around API endpoints, request parameters and response objects. If any questions remain unanswered for you, simply reach out to the aviationstack support team for assistance.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DataFlight2Codeshared(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'airline_name': 'str',
        'airline_iata': 'str',
        'airline_icao': 'str',
        'flight_number': 'str',
        'flight_iata': 'str',
        'flight_icao': 'str'
    }

    attribute_map = {
        'airline_name': 'airline_name',
        'airline_iata': 'airline_iata',
        'airline_icao': 'airline_icao',
        'flight_number': 'flight_number',
        'flight_iata': 'flight_iata',
        'flight_icao': 'flight_icao'
    }

    def __init__(self, airline_name=None, airline_iata=None, airline_icao=None, flight_number=None, flight_iata=None, flight_icao=None):  # noqa: E501
        """DataFlight2Codeshared - a model defined in Swagger"""  # noqa: E501
        self._airline_name = None
        self._airline_iata = None
        self._airline_icao = None
        self._flight_number = None
        self._flight_iata = None
        self._flight_icao = None
        self.discriminator = None
        if airline_name is not None:
            self.airline_name = airline_name
        if airline_iata is not None:
            self.airline_iata = airline_iata
        if airline_icao is not None:
            self.airline_icao = airline_icao
        if flight_number is not None:
            self.flight_number = flight_number
        if flight_iata is not None:
            self.flight_iata = flight_iata
        if flight_icao is not None:
            self.flight_icao = flight_icao

    @property
    def airline_name(self):
        """Gets the airline_name of this DataFlight2Codeshared.  # noqa: E501


        :return: The airline_name of this DataFlight2Codeshared.  # noqa: E501
        :rtype: str
        """
        return self._airline_name

    @airline_name.setter
    def airline_name(self, airline_name):
        """Sets the airline_name of this DataFlight2Codeshared.


        :param airline_name: The airline_name of this DataFlight2Codeshared.  # noqa: E501
        :type: str
        """

        self._airline_name = airline_name

    @property
    def airline_iata(self):
        """Gets the airline_iata of this DataFlight2Codeshared.  # noqa: E501


        :return: The airline_iata of this DataFlight2Codeshared.  # noqa: E501
        :rtype: str
        """
        return self._airline_iata

    @airline_iata.setter
    def airline_iata(self, airline_iata):
        """Sets the airline_iata of this DataFlight2Codeshared.


        :param airline_iata: The airline_iata of this DataFlight2Codeshared.  # noqa: E501
        :type: str
        """

        self._airline_iata = airline_iata

    @property
    def airline_icao(self):
        """Gets the airline_icao of this DataFlight2Codeshared.  # noqa: E501


        :return: The airline_icao of this DataFlight2Codeshared.  # noqa: E501
        :rtype: str
        """
        return self._airline_icao

    @airline_icao.setter
    def airline_icao(self, airline_icao):
        """Sets the airline_icao of this DataFlight2Codeshared.


        :param airline_icao: The airline_icao of this DataFlight2Codeshared.  # noqa: E501
        :type: str
        """

        self._airline_icao = airline_icao

    @property
    def flight_number(self):
        """Gets the flight_number of this DataFlight2Codeshared.  # noqa: E501


        :return: The flight_number of this DataFlight2Codeshared.  # noqa: E501
        :rtype: str
        """
        return self._flight_number

    @flight_number.setter
    def flight_number(self, flight_number):
        """Sets the flight_number of this DataFlight2Codeshared.


        :param flight_number: The flight_number of this DataFlight2Codeshared.  # noqa: E501
        :type: str
        """

        self._flight_number = flight_number

    @property
    def flight_iata(self):
        """Gets the flight_iata of this DataFlight2Codeshared.  # noqa: E501


        :return: The flight_iata of this DataFlight2Codeshared.  # noqa: E501
        :rtype: str
        """
        return self._flight_iata

    @flight_iata.setter
    def flight_iata(self, flight_iata):
        """Sets the flight_iata of this DataFlight2Codeshared.


        :param flight_iata: The flight_iata of this DataFlight2Codeshared.  # noqa: E501
        :type: str
        """

        self._flight_iata = flight_iata

    @property
    def flight_icao(self):
        """Gets the flight_icao of this DataFlight2Codeshared.  # noqa: E501


        :return: The flight_icao of this DataFlight2Codeshared.  # noqa: E501
        :rtype: str
        """
        return self._flight_icao

    @flight_icao.setter
    def flight_icao(self, flight_icao):
        """Sets the flight_icao of this DataFlight2Codeshared.


        :param flight_icao: The flight_icao of this DataFlight2Codeshared.  # noqa: E501
        :type: str
        """

        self._flight_icao = flight_icao

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DataFlight2Codeshared, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DataFlight2Codeshared):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
