# coding: utf-8

"""
    AviationStack

    The aviationstack API was built to provide a simple way of accessing global aviation data for real-time and historical flights as well as allow customers to tap into an extensive data set of airline routes and other up-to-date aviation-related information. Requests to the REST API are made using a straightforward HTTP GET URL structure and responses are provided in lightweight JSON format. The following API documentation can be applied for any major programming language and will present general integration guides and explanations around API endpoints, request parameters and response objects. If any questions remain unanswered for you, simply reach out to the aviationstack support team for assistance.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Datalive(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'updated': 'str',
        'latitude': 'float',
        'longitude': 'float',
        'altitude': 'float',
        'direction': 'float',
        'speed_horizontal': 'float',
        'speed_vertical': 'float',
        'is_ground': 'bool'
    }

    attribute_map = {
        'updated': 'updated',
        'latitude': 'latitude',
        'longitude': 'longitude',
        'altitude': 'altitude',
        'direction': 'direction',
        'speed_horizontal': 'speed_horizontal',
        'speed_vertical': 'speed_vertical',
        'is_ground': 'is_ground'
    }

    def __init__(self, updated=None, latitude=None, longitude=None, altitude=None, direction=None, speed_horizontal=None, speed_vertical=None, is_ground=None):  # noqa: E501
        """Datalive - a model defined in Swagger"""  # noqa: E501
        self._updated = None
        self._latitude = None
        self._longitude = None
        self._altitude = None
        self._direction = None
        self._speed_horizontal = None
        self._speed_vertical = None
        self._is_ground = None
        self.discriminator = None
        if updated is not None:
            self.updated = updated
        if latitude is not None:
            self.latitude = latitude
        if longitude is not None:
            self.longitude = longitude
        if altitude is not None:
            self.altitude = altitude
        if direction is not None:
            self.direction = direction
        if speed_horizontal is not None:
            self.speed_horizontal = speed_horizontal
        if speed_vertical is not None:
            self.speed_vertical = speed_vertical
        if is_ground is not None:
            self.is_ground = is_ground

    @property
    def updated(self):
        """Gets the updated of this Datalive.  # noqa: E501


        :return: The updated of this Datalive.  # noqa: E501
        :rtype: str
        """
        return self._updated

    @updated.setter
    def updated(self, updated):
        """Sets the updated of this Datalive.


        :param updated: The updated of this Datalive.  # noqa: E501
        :type: str
        """

        self._updated = updated

    @property
    def latitude(self):
        """Gets the latitude of this Datalive.  # noqa: E501


        :return: The latitude of this Datalive.  # noqa: E501
        :rtype: float
        """
        return self._latitude

    @latitude.setter
    def latitude(self, latitude):
        """Sets the latitude of this Datalive.


        :param latitude: The latitude of this Datalive.  # noqa: E501
        :type: float
        """

        self._latitude = latitude

    @property
    def longitude(self):
        """Gets the longitude of this Datalive.  # noqa: E501


        :return: The longitude of this Datalive.  # noqa: E501
        :rtype: float
        """
        return self._longitude

    @longitude.setter
    def longitude(self, longitude):
        """Sets the longitude of this Datalive.


        :param longitude: The longitude of this Datalive.  # noqa: E501
        :type: float
        """

        self._longitude = longitude

    @property
    def altitude(self):
        """Gets the altitude of this Datalive.  # noqa: E501


        :return: The altitude of this Datalive.  # noqa: E501
        :rtype: float
        """
        return self._altitude

    @altitude.setter
    def altitude(self, altitude):
        """Sets the altitude of this Datalive.


        :param altitude: The altitude of this Datalive.  # noqa: E501
        :type: float
        """

        self._altitude = altitude

    @property
    def direction(self):
        """Gets the direction of this Datalive.  # noqa: E501


        :return: The direction of this Datalive.  # noqa: E501
        :rtype: float
        """
        return self._direction

    @direction.setter
    def direction(self, direction):
        """Sets the direction of this Datalive.


        :param direction: The direction of this Datalive.  # noqa: E501
        :type: float
        """

        self._direction = direction

    @property
    def speed_horizontal(self):
        """Gets the speed_horizontal of this Datalive.  # noqa: E501


        :return: The speed_horizontal of this Datalive.  # noqa: E501
        :rtype: float
        """
        return self._speed_horizontal

    @speed_horizontal.setter
    def speed_horizontal(self, speed_horizontal):
        """Sets the speed_horizontal of this Datalive.


        :param speed_horizontal: The speed_horizontal of this Datalive.  # noqa: E501
        :type: float
        """

        self._speed_horizontal = speed_horizontal

    @property
    def speed_vertical(self):
        """Gets the speed_vertical of this Datalive.  # noqa: E501


        :return: The speed_vertical of this Datalive.  # noqa: E501
        :rtype: float
        """
        return self._speed_vertical

    @speed_vertical.setter
    def speed_vertical(self, speed_vertical):
        """Sets the speed_vertical of this Datalive.


        :param speed_vertical: The speed_vertical of this Datalive.  # noqa: E501
        :type: float
        """

        self._speed_vertical = speed_vertical

    @property
    def is_ground(self):
        """Gets the is_ground of this Datalive.  # noqa: E501


        :return: The is_ground of this Datalive.  # noqa: E501
        :rtype: bool
        """
        return self._is_ground

    @is_ground.setter
    def is_ground(self, is_ground):
        """Sets the is_ground of this Datalive.


        :param is_ground: The is_ground of this Datalive.  # noqa: E501
        :type: bool
        """

        self._is_ground = is_ground

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Datalive, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Datalive):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
