# coding: utf-8

"""
    AviationStack

    The aviationstack API was built to provide a simple way of accessing global aviation data for real-time and historical flights as well as allow customers to tap into an extensive data set of airline routes and other up-to-date aviation-related information. Requests to the REST API are made using a straightforward HTTP GET URL structure and responses are provided in lightweight JSON format. The following API documentation can be applied for any major programming language and will present general integration guides and explanations around API endpoints, request parameters and response objects. If any questions remain unanswered for you, simply reach out to the aviationstack support team for assistance.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DataAircraft(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'registration': 'str',
        'iata': 'str',
        'icao': 'str',
        'icao24': 'str'
    }

    attribute_map = {
        'registration': 'registration',
        'iata': 'iata',
        'icao': 'icao',
        'icao24': 'icao24'
    }

    def __init__(self, registration=None, iata=None, icao=None, icao24=None):  # noqa: E501
        """DataAircraft - a model defined in Swagger"""  # noqa: E501
        self._registration = None
        self._iata = None
        self._icao = None
        self._icao24 = None
        self.discriminator = None
        if registration is not None:
            self.registration = registration
        if iata is not None:
            self.iata = iata
        if icao is not None:
            self.icao = icao
        if icao24 is not None:
            self.icao24 = icao24

    @property
    def registration(self):
        """Gets the registration of this DataAircraft.  # noqa: E501


        :return: The registration of this DataAircraft.  # noqa: E501
        :rtype: str
        """
        return self._registration

    @registration.setter
    def registration(self, registration):
        """Sets the registration of this DataAircraft.


        :param registration: The registration of this DataAircraft.  # noqa: E501
        :type: str
        """

        self._registration = registration

    @property
    def iata(self):
        """Gets the iata of this DataAircraft.  # noqa: E501


        :return: The iata of this DataAircraft.  # noqa: E501
        :rtype: str
        """
        return self._iata

    @iata.setter
    def iata(self, iata):
        """Sets the iata of this DataAircraft.


        :param iata: The iata of this DataAircraft.  # noqa: E501
        :type: str
        """

        self._iata = iata

    @property
    def icao(self):
        """Gets the icao of this DataAircraft.  # noqa: E501


        :return: The icao of this DataAircraft.  # noqa: E501
        :rtype: str
        """
        return self._icao

    @icao.setter
    def icao(self, icao):
        """Sets the icao of this DataAircraft.


        :param icao: The icao of this DataAircraft.  # noqa: E501
        :type: str
        """

        self._icao = icao

    @property
    def icao24(self):
        """Gets the icao24 of this DataAircraft.  # noqa: E501


        :return: The icao24 of this DataAircraft.  # noqa: E501
        :rtype: str
        """
        return self._icao24

    @icao24.setter
    def icao24(self, icao24):
        """Sets the icao24 of this DataAircraft.


        :param icao24: The icao24 of this DataAircraft.  # noqa: E501
        :type: str
        """

        self._icao24 = icao24

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DataAircraft, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DataAircraft):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
