# coding: utf-8

"""
    AviationStack

    The aviationstack API was built to provide a simple way of accessing global aviation data for real-time and historical flights as well as allow customers to tap into an extensive data set of airline routes and other up-to-date aviation-related information. Requests to the REST API are made using a straightforward HTTP GET URL structure and responses are provided in lightweight JSON format. The following API documentation can be applied for any major programming language and will present general integration guides and explanations around API endpoints, request parameters and response objects. If any questions remain unanswered for you, simply reach out to the aviationstack support team for assistance.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class FlightsFuture(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'pagination': 'Pagination',
        'data': 'list[FutureFlightData]'
    }

    attribute_map = {
        'pagination': 'pagination',
        'data': 'data'
    }

    def __init__(self, pagination=None, data=None):  # noqa: E501
        """FlightsFuture - a model defined in Swagger"""  # noqa: E501
        self._pagination = None
        self._data = None
        self.discriminator = None
        if pagination is not None:
            self.pagination = pagination
        if data is not None:
            self.data = data

    @property
    def pagination(self):
        """Gets the pagination of this FlightsFuture.  # noqa: E501


        :return: The pagination of this FlightsFuture.  # noqa: E501
        :rtype: Pagination
        """
        return self._pagination

    @pagination.setter
    def pagination(self, pagination):
        """Sets the pagination of this FlightsFuture.


        :param pagination: The pagination of this FlightsFuture.  # noqa: E501
        :type: Pagination
        """

        self._pagination = pagination

    @property
    def data(self):
        """Gets the data of this FlightsFuture.  # noqa: E501


        :return: The data of this FlightsFuture.  # noqa: E501
        :rtype: list[FutureFlightData]
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this FlightsFuture.


        :param data: The data of this FlightsFuture.  # noqa: E501
        :type: list[FutureFlightData]
        """

        self._data = data

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(FlightsFuture, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FlightsFuture):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
