# coding: utf-8

"""
    AviationStack

    The aviationstack API was built to provide a simple way of accessing global aviation data for real-time and historical flights as well as allow customers to tap into an extensive data set of airline routes and other up-to-date aviation-related information. Requests to the REST API are made using a straightforward HTTP GET URL structure and responses are provided in lightweight JSON format. The following API documentation can be applied for any major programming language and will present general integration guides and explanations around API endpoints, request parameters and response objects. If any questions remain unanswered for you, simply reach out to the aviationstack support team for assistance.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class FutureFlightPoint(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'iata_code': 'str',
        'icao_code': 'str',
        'terminal': 'str',
        'gate': 'str',
        'scheduled_time': 'str'
    }

    attribute_map = {
        'iata_code': 'iataCode',
        'icao_code': 'icaoCode',
        'terminal': 'terminal',
        'gate': 'gate',
        'scheduled_time': 'scheduledTime'
    }

    def __init__(self, iata_code=None, icao_code=None, terminal=None, gate=None, scheduled_time=None):  # noqa: E501
        """FutureFlightPoint - a model defined in Swagger"""  # noqa: E501
        self._iata_code = None
        self._icao_code = None
        self._terminal = None
        self._gate = None
        self._scheduled_time = None
        self.discriminator = None
        if iata_code is not None:
            self.iata_code = iata_code
        if icao_code is not None:
            self.icao_code = icao_code
        if terminal is not None:
            self.terminal = terminal
        if gate is not None:
            self.gate = gate
        if scheduled_time is not None:
            self.scheduled_time = scheduled_time

    @property
    def iata_code(self):
        """Gets the iata_code of this FutureFlightPoint.  # noqa: E501


        :return: The iata_code of this FutureFlightPoint.  # noqa: E501
        :rtype: str
        """
        return self._iata_code

    @iata_code.setter
    def iata_code(self, iata_code):
        """Sets the iata_code of this FutureFlightPoint.


        :param iata_code: The iata_code of this FutureFlightPoint.  # noqa: E501
        :type: str
        """

        self._iata_code = iata_code

    @property
    def icao_code(self):
        """Gets the icao_code of this FutureFlightPoint.  # noqa: E501


        :return: The icao_code of this FutureFlightPoint.  # noqa: E501
        :rtype: str
        """
        return self._icao_code

    @icao_code.setter
    def icao_code(self, icao_code):
        """Sets the icao_code of this FutureFlightPoint.


        :param icao_code: The icao_code of this FutureFlightPoint.  # noqa: E501
        :type: str
        """

        self._icao_code = icao_code

    @property
    def terminal(self):
        """Gets the terminal of this FutureFlightPoint.  # noqa: E501


        :return: The terminal of this FutureFlightPoint.  # noqa: E501
        :rtype: str
        """
        return self._terminal

    @terminal.setter
    def terminal(self, terminal):
        """Sets the terminal of this FutureFlightPoint.


        :param terminal: The terminal of this FutureFlightPoint.  # noqa: E501
        :type: str
        """

        self._terminal = terminal

    @property
    def gate(self):
        """Gets the gate of this FutureFlightPoint.  # noqa: E501


        :return: The gate of this FutureFlightPoint.  # noqa: E501
        :rtype: str
        """
        return self._gate

    @gate.setter
    def gate(self, gate):
        """Sets the gate of this FutureFlightPoint.


        :param gate: The gate of this FutureFlightPoint.  # noqa: E501
        :type: str
        """

        self._gate = gate

    @property
    def scheduled_time(self):
        """Gets the scheduled_time of this FutureFlightPoint.  # noqa: E501


        :return: The scheduled_time of this FutureFlightPoint.  # noqa: E501
        :rtype: str
        """
        return self._scheduled_time

    @scheduled_time.setter
    def scheduled_time(self, scheduled_time):
        """Sets the scheduled_time of this FutureFlightPoint.


        :param scheduled_time: The scheduled_time of this FutureFlightPoint.  # noqa: E501
        :type: str
        """

        self._scheduled_time = scheduled_time

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(FutureFlightPoint, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FutureFlightPoint):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
