# coding: utf-8

"""
    AviationStack

    The aviationstack API was built to provide a simple way of accessing global aviation data for real-time and historical flights as well as allow customers to tap into an extensive data set of airline routes and other up-to-date aviation-related information. Requests to the REST API are made using a straightforward HTTP GET URL structure and responses are provided in lightweight JSON format. The following API documentation can be applied for any major programming language and will present general integration guides and explanations around API endpoints, request parameters and response objects. If any questions remain unanswered for you, simply reach out to the aviationstack support team for assistance.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class FutureFlightAirline(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'iata_code': 'str',
        'icao_code': 'str'
    }

    attribute_map = {
        'name': 'name',
        'iata_code': 'iataCode',
        'icao_code': 'icaoCode'
    }

    def __init__(self, name=None, iata_code=None, icao_code=None):  # noqa: E501
        """FutureFlightAirline - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._iata_code = None
        self._icao_code = None
        self.discriminator = None
        if name is not None:
            self.name = name
        if iata_code is not None:
            self.iata_code = iata_code
        if icao_code is not None:
            self.icao_code = icao_code

    @property
    def name(self):
        """Gets the name of this FutureFlightAirline.  # noqa: E501


        :return: The name of this FutureFlightAirline.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this FutureFlightAirline.


        :param name: The name of this FutureFlightAirline.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def iata_code(self):
        """Gets the iata_code of this FutureFlightAirline.  # noqa: E501


        :return: The iata_code of this FutureFlightAirline.  # noqa: E501
        :rtype: str
        """
        return self._iata_code

    @iata_code.setter
    def iata_code(self, iata_code):
        """Sets the iata_code of this FutureFlightAirline.


        :param iata_code: The iata_code of this FutureFlightAirline.  # noqa: E501
        :type: str
        """

        self._iata_code = iata_code

    @property
    def icao_code(self):
        """Gets the icao_code of this FutureFlightAirline.  # noqa: E501


        :return: The icao_code of this FutureFlightAirline.  # noqa: E501
        :rtype: str
        """
        return self._icao_code

    @icao_code.setter
    def icao_code(self, icao_code):
        """Sets the icao_code of this FutureFlightAirline.


        :param icao_code: The icao_code of this FutureFlightAirline.  # noqa: E501
        :type: str
        """

        self._icao_code = icao_code

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(FutureFlightAirline, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FutureFlightAirline):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
