# coding: utf-8

"""
    AviationStack

    The aviationstack API was built to provide a simple way of accessing global aviation data for real-time and historical flights as well as allow customers to tap into an extensive data set of airline routes and other up-to-date aviation-related information. Requests to the REST API are made using a straightforward HTTP GET URL structure and responses are provided in lightweight JSON format. The following API documentation can be applied for any major programming language and will present general integration guides and explanations around API endpoints, request parameters and response objects. If any questions remain unanswered for you, simply reach out to the aviationstack support team for assistance.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class FutureFlightAircraft(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'model_code': 'str',
        'model_text': 'str'
    }

    attribute_map = {
        'model_code': 'modelCode',
        'model_text': 'modelText'
    }

    def __init__(self, model_code=None, model_text=None):  # noqa: E501
        """FutureFlightAircraft - a model defined in Swagger"""  # noqa: E501
        self._model_code = None
        self._model_text = None
        self.discriminator = None
        if model_code is not None:
            self.model_code = model_code
        if model_text is not None:
            self.model_text = model_text

    @property
    def model_code(self):
        """Gets the model_code of this FutureFlightAircraft.  # noqa: E501


        :return: The model_code of this FutureFlightAircraft.  # noqa: E501
        :rtype: str
        """
        return self._model_code

    @model_code.setter
    def model_code(self, model_code):
        """Sets the model_code of this FutureFlightAircraft.


        :param model_code: The model_code of this FutureFlightAircraft.  # noqa: E501
        :type: str
        """

        self._model_code = model_code

    @property
    def model_text(self):
        """Gets the model_text of this FutureFlightAircraft.  # noqa: E501


        :return: The model_text of this FutureFlightAircraft.  # noqa: E501
        :rtype: str
        """
        return self._model_text

    @model_text.setter
    def model_text(self, model_text):
        """Sets the model_text of this FutureFlightAircraft.


        :param model_text: The model_text of this FutureFlightAircraft.  # noqa: E501
        :type: str
        """

        self._model_text = model_text

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(FutureFlightAircraft, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FutureFlightAircraft):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
