# coding: utf-8

"""
    AviationStack

    The aviationstack API was built to provide a simple way of accessing global aviation data for real-time and historical flights as well as allow customers to tap into an extensive data set of airline routes and other up-to-date aviation-related information. Requests to the REST API are made using a straightforward HTTP GET URL structure and responses are provided in lightweight JSON format. The following API documentation can be applied for any major programming language and will present general integration guides and explanations around API endpoints, request parameters and response objects. If any questions remain unanswered for you, simply reach out to the aviationstack support team for assistance.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class FutureFlightData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'weekday': 'str',
        'departure': 'FutureFlightPoint',
        'arrival': 'FutureFlightPoint',
        'aircraft': 'FutureFlightAircraft',
        'airline': 'FutureFlightAirline',
        'flight': 'FutureFlightInfo',
        'codeshared': 'FutureFlightDataCodeshared'
    }

    attribute_map = {
        'weekday': 'weekday',
        'departure': 'departure',
        'arrival': 'arrival',
        'aircraft': 'aircraft',
        'airline': 'airline',
        'flight': 'flight',
        'codeshared': 'codeshared'
    }

    def __init__(self, weekday=None, departure=None, arrival=None, aircraft=None, airline=None, flight=None, codeshared=None):  # noqa: E501
        """FutureFlightData - a model defined in Swagger"""  # noqa: E501
        self._weekday = None
        self._departure = None
        self._arrival = None
        self._aircraft = None
        self._airline = None
        self._flight = None
        self._codeshared = None
        self.discriminator = None
        if weekday is not None:
            self.weekday = weekday
        if departure is not None:
            self.departure = departure
        if arrival is not None:
            self.arrival = arrival
        if aircraft is not None:
            self.aircraft = aircraft
        if airline is not None:
            self.airline = airline
        if flight is not None:
            self.flight = flight
        if codeshared is not None:
            self.codeshared = codeshared

    @property
    def weekday(self):
        """Gets the weekday of this FutureFlightData.  # noqa: E501


        :return: The weekday of this FutureFlightData.  # noqa: E501
        :rtype: str
        """
        return self._weekday

    @weekday.setter
    def weekday(self, weekday):
        """Sets the weekday of this FutureFlightData.


        :param weekday: The weekday of this FutureFlightData.  # noqa: E501
        :type: str
        """

        self._weekday = weekday

    @property
    def departure(self):
        """Gets the departure of this FutureFlightData.  # noqa: E501


        :return: The departure of this FutureFlightData.  # noqa: E501
        :rtype: FutureFlightPoint
        """
        return self._departure

    @departure.setter
    def departure(self, departure):
        """Sets the departure of this FutureFlightData.


        :param departure: The departure of this FutureFlightData.  # noqa: E501
        :type: FutureFlightPoint
        """

        self._departure = departure

    @property
    def arrival(self):
        """Gets the arrival of this FutureFlightData.  # noqa: E501


        :return: The arrival of this FutureFlightData.  # noqa: E501
        :rtype: FutureFlightPoint
        """
        return self._arrival

    @arrival.setter
    def arrival(self, arrival):
        """Sets the arrival of this FutureFlightData.


        :param arrival: The arrival of this FutureFlightData.  # noqa: E501
        :type: FutureFlightPoint
        """

        self._arrival = arrival

    @property
    def aircraft(self):
        """Gets the aircraft of this FutureFlightData.  # noqa: E501


        :return: The aircraft of this FutureFlightData.  # noqa: E501
        :rtype: FutureFlightAircraft
        """
        return self._aircraft

    @aircraft.setter
    def aircraft(self, aircraft):
        """Sets the aircraft of this FutureFlightData.


        :param aircraft: The aircraft of this FutureFlightData.  # noqa: E501
        :type: FutureFlightAircraft
        """

        self._aircraft = aircraft

    @property
    def airline(self):
        """Gets the airline of this FutureFlightData.  # noqa: E501


        :return: The airline of this FutureFlightData.  # noqa: E501
        :rtype: FutureFlightAirline
        """
        return self._airline

    @airline.setter
    def airline(self, airline):
        """Sets the airline of this FutureFlightData.


        :param airline: The airline of this FutureFlightData.  # noqa: E501
        :type: FutureFlightAirline
        """

        self._airline = airline

    @property
    def flight(self):
        """Gets the flight of this FutureFlightData.  # noqa: E501


        :return: The flight of this FutureFlightData.  # noqa: E501
        :rtype: FutureFlightInfo
        """
        return self._flight

    @flight.setter
    def flight(self, flight):
        """Sets the flight of this FutureFlightData.


        :param flight: The flight of this FutureFlightData.  # noqa: E501
        :type: FutureFlightInfo
        """

        self._flight = flight

    @property
    def codeshared(self):
        """Gets the codeshared of this FutureFlightData.  # noqa: E501


        :return: The codeshared of this FutureFlightData.  # noqa: E501
        :rtype: FutureFlightDataCodeshared
        """
        return self._codeshared

    @codeshared.setter
    def codeshared(self, codeshared):
        """Sets the codeshared of this FutureFlightData.


        :param codeshared: The codeshared of this FutureFlightData.  # noqa: E501
        :type: FutureFlightDataCodeshared
        """

        self._codeshared = codeshared

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(FutureFlightData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FutureFlightData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
