# coding: utf-8

"""
    AviationStack

    The aviationstack API was built to provide a simple way of accessing global aviation data for real-time and historical flights as well as allow customers to tap into an extensive data set of airline routes and other up-to-date aviation-related information. Requests to the REST API are made using a straightforward HTTP GET URL structure and responses are provided in lightweight JSON format. The following API documentation can be applied for any major programming language and will present general integration guides and explanations around API endpoints, request parameters and response objects. If any questions remain unanswered for you, simply reach out to the aviationstack support team for assistance.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class RouteEndpoint(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'airport': 'str',
        'timezone': 'str',
        'iata': 'str',
        'icao': 'str',
        'terminal': 'str',
        'time': 'str'
    }

    attribute_map = {
        'airport': 'airport',
        'timezone': 'timezone',
        'iata': 'iata',
        'icao': 'icao',
        'terminal': 'terminal',
        'time': 'time'
    }

    def __init__(self, airport=None, timezone=None, iata=None, icao=None, terminal=None, time=None):  # noqa: E501
        """RouteEndpoint - a model defined in Swagger"""  # noqa: E501
        self._airport = None
        self._timezone = None
        self._iata = None
        self._icao = None
        self._terminal = None
        self._time = None
        self.discriminator = None
        if airport is not None:
            self.airport = airport
        if timezone is not None:
            self.timezone = timezone
        if iata is not None:
            self.iata = iata
        if icao is not None:
            self.icao = icao
        if terminal is not None:
            self.terminal = terminal
        if time is not None:
            self.time = time

    @property
    def airport(self):
        """Gets the airport of this RouteEndpoint.  # noqa: E501


        :return: The airport of this RouteEndpoint.  # noqa: E501
        :rtype: str
        """
        return self._airport

    @airport.setter
    def airport(self, airport):
        """Sets the airport of this RouteEndpoint.


        :param airport: The airport of this RouteEndpoint.  # noqa: E501
        :type: str
        """

        self._airport = airport

    @property
    def timezone(self):
        """Gets the timezone of this RouteEndpoint.  # noqa: E501


        :return: The timezone of this RouteEndpoint.  # noqa: E501
        :rtype: str
        """
        return self._timezone

    @timezone.setter
    def timezone(self, timezone):
        """Sets the timezone of this RouteEndpoint.


        :param timezone: The timezone of this RouteEndpoint.  # noqa: E501
        :type: str
        """

        self._timezone = timezone

    @property
    def iata(self):
        """Gets the iata of this RouteEndpoint.  # noqa: E501


        :return: The iata of this RouteEndpoint.  # noqa: E501
        :rtype: str
        """
        return self._iata

    @iata.setter
    def iata(self, iata):
        """Sets the iata of this RouteEndpoint.


        :param iata: The iata of this RouteEndpoint.  # noqa: E501
        :type: str
        """

        self._iata = iata

    @property
    def icao(self):
        """Gets the icao of this RouteEndpoint.  # noqa: E501


        :return: The icao of this RouteEndpoint.  # noqa: E501
        :rtype: str
        """
        return self._icao

    @icao.setter
    def icao(self, icao):
        """Sets the icao of this RouteEndpoint.


        :param icao: The icao of this RouteEndpoint.  # noqa: E501
        :type: str
        """

        self._icao = icao

    @property
    def terminal(self):
        """Gets the terminal of this RouteEndpoint.  # noqa: E501


        :return: The terminal of this RouteEndpoint.  # noqa: E501
        :rtype: str
        """
        return self._terminal

    @terminal.setter
    def terminal(self, terminal):
        """Sets the terminal of this RouteEndpoint.


        :param terminal: The terminal of this RouteEndpoint.  # noqa: E501
        :type: str
        """

        self._terminal = terminal

    @property
    def time(self):
        """Gets the time of this RouteEndpoint.  # noqa: E501


        :return: The time of this RouteEndpoint.  # noqa: E501
        :rtype: str
        """
        return self._time

    @time.setter
    def time(self, time):
        """Sets the time of this RouteEndpoint.


        :param time: The time of this RouteEndpoint.  # noqa: E501
        :type: str
        """

        self._time = time

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RouteEndpoint, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RouteEndpoint):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
