# coding: utf-8

"""
    AviationStack

    The aviationstack API was built to provide a simple way of accessing global aviation data for real-time and historical flights as well as allow customers to tap into an extensive data set of airline routes and other up-to-date aviation-related information. Requests to the REST API are made using a straightforward HTTP GET URL structure and responses are provided in lightweight JSON format. The following API documentation can be applied for any major programming language and will present general integration guides and explanations around API endpoints, request parameters and response objects. If any questions remain unanswered for you, simply reach out to the aviationstack support team for assistance.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class TaxData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'tax_id': 'str',
        'tax_name': 'str',
        'iata_code': 'str'
    }

    attribute_map = {
        'id': 'id',
        'tax_id': 'tax_id',
        'tax_name': 'tax_name',
        'iata_code': 'iata_code'
    }

    def __init__(self, id=None, tax_id=None, tax_name=None, iata_code=None):  # noqa: E501
        """TaxData - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._tax_id = None
        self._tax_name = None
        self._iata_code = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if tax_id is not None:
            self.tax_id = tax_id
        if tax_name is not None:
            self.tax_name = tax_name
        if iata_code is not None:
            self.iata_code = iata_code

    @property
    def id(self):
        """Gets the id of this TaxData.  # noqa: E501


        :return: The id of this TaxData.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this TaxData.


        :param id: The id of this TaxData.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def tax_id(self):
        """Gets the tax_id of this TaxData.  # noqa: E501


        :return: The tax_id of this TaxData.  # noqa: E501
        :rtype: str
        """
        return self._tax_id

    @tax_id.setter
    def tax_id(self, tax_id):
        """Sets the tax_id of this TaxData.


        :param tax_id: The tax_id of this TaxData.  # noqa: E501
        :type: str
        """

        self._tax_id = tax_id

    @property
    def tax_name(self):
        """Gets the tax_name of this TaxData.  # noqa: E501


        :return: The tax_name of this TaxData.  # noqa: E501
        :rtype: str
        """
        return self._tax_name

    @tax_name.setter
    def tax_name(self, tax_name):
        """Sets the tax_name of this TaxData.


        :param tax_name: The tax_name of this TaxData.  # noqa: E501
        :type: str
        """

        self._tax_name = tax_name

    @property
    def iata_code(self):
        """Gets the iata_code of this TaxData.  # noqa: E501


        :return: The iata_code of this TaxData.  # noqa: E501
        :rtype: str
        """
        return self._iata_code

    @iata_code.setter
    def iata_code(self, iata_code):
        """Sets the iata_code of this TaxData.


        :param iata_code: The iata_code of this TaxData.  # noqa: E501
        :type: str
        """

        self._iata_code = iata_code

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TaxData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TaxData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
