# coding: utf-8

"""
    AviationStack

    The aviationstack API was built to provide a simple way of accessing global aviation data for real-time and historical flights as well as allow customers to tap into an extensive data set of airline routes and other up-to-date aviation-related information. Requests to the REST API are made using a straightforward HTTP GET URL structure and responses are provided in lightweight JSON format. The following API documentation can be applied for any major programming language and will present general integration guides and explanations around API endpoints, request parameters and response objects. If any questions remain unanswered for you, simply reach out to the aviationstack support team for assistance.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class TimetableAircraft(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'icao24': 'str',
        'icao_code': 'str',
        'reg_number': 'str'
    }

    attribute_map = {
        'icao24': 'icao24',
        'icao_code': 'icaoCode',
        'reg_number': 'regNumber'
    }

    def __init__(self, icao24=None, icao_code=None, reg_number=None):  # noqa: E501
        """TimetableAircraft - a model defined in Swagger"""  # noqa: E501
        self._icao24 = None
        self._icao_code = None
        self._reg_number = None
        self.discriminator = None
        if icao24 is not None:
            self.icao24 = icao24
        if icao_code is not None:
            self.icao_code = icao_code
        if reg_number is not None:
            self.reg_number = reg_number

    @property
    def icao24(self):
        """Gets the icao24 of this TimetableAircraft.  # noqa: E501


        :return: The icao24 of this TimetableAircraft.  # noqa: E501
        :rtype: str
        """
        return self._icao24

    @icao24.setter
    def icao24(self, icao24):
        """Sets the icao24 of this TimetableAircraft.


        :param icao24: The icao24 of this TimetableAircraft.  # noqa: E501
        :type: str
        """

        self._icao24 = icao24

    @property
    def icao_code(self):
        """Gets the icao_code of this TimetableAircraft.  # noqa: E501


        :return: The icao_code of this TimetableAircraft.  # noqa: E501
        :rtype: str
        """
        return self._icao_code

    @icao_code.setter
    def icao_code(self, icao_code):
        """Sets the icao_code of this TimetableAircraft.


        :param icao_code: The icao_code of this TimetableAircraft.  # noqa: E501
        :type: str
        """

        self._icao_code = icao_code

    @property
    def reg_number(self):
        """Gets the reg_number of this TimetableAircraft.  # noqa: E501


        :return: The reg_number of this TimetableAircraft.  # noqa: E501
        :rtype: str
        """
        return self._reg_number

    @reg_number.setter
    def reg_number(self, reg_number):
        """Sets the reg_number of this TimetableAircraft.


        :param reg_number: The reg_number of this TimetableAircraft.  # noqa: E501
        :type: str
        """

        self._reg_number = reg_number

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TimetableAircraft, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TimetableAircraft):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
