# coding: utf-8

"""
    AviationStack

    The aviationstack API was built to provide a simple way of accessing global aviation data for real-time and historical flights as well as allow customers to tap into an extensive data set of airline routes and other up-to-date aviation-related information. Requests to the REST API are made using a straightforward HTTP GET URL structure and responses are provided in lightweight JSON format. The following API documentation can be applied for any major programming language and will present general integration guides and explanations around API endpoints, request parameters and response objects. If any questions remain unanswered for you, simply reach out to the aviationstack support team for assistance.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class TimetableData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'aircraft': 'TimetableAircraft',
        'airline': 'TimetableAirline',
        'arrival': 'TimetableSchedule',
        'codeshared': 'TimetableDataCodeshared',
        'departure': 'TimetableSchedule',
        'flight': 'TimetableFlight',
        'status': 'str',
        'type': 'str'
    }

    attribute_map = {
        'aircraft': 'aircraft',
        'airline': 'airline',
        'arrival': 'arrival',
        'codeshared': 'codeshared',
        'departure': 'departure',
        'flight': 'flight',
        'status': 'status',
        'type': 'type'
    }

    def __init__(self, aircraft=None, airline=None, arrival=None, codeshared=None, departure=None, flight=None, status=None, type=None):  # noqa: E501
        """TimetableData - a model defined in Swagger"""  # noqa: E501
        self._aircraft = None
        self._airline = None
        self._arrival = None
        self._codeshared = None
        self._departure = None
        self._flight = None
        self._status = None
        self._type = None
        self.discriminator = None
        if aircraft is not None:
            self.aircraft = aircraft
        if airline is not None:
            self.airline = airline
        if arrival is not None:
            self.arrival = arrival
        if codeshared is not None:
            self.codeshared = codeshared
        if departure is not None:
            self.departure = departure
        if flight is not None:
            self.flight = flight
        if status is not None:
            self.status = status
        if type is not None:
            self.type = type

    @property
    def aircraft(self):
        """Gets the aircraft of this TimetableData.  # noqa: E501


        :return: The aircraft of this TimetableData.  # noqa: E501
        :rtype: TimetableAircraft
        """
        return self._aircraft

    @aircraft.setter
    def aircraft(self, aircraft):
        """Sets the aircraft of this TimetableData.


        :param aircraft: The aircraft of this TimetableData.  # noqa: E501
        :type: TimetableAircraft
        """

        self._aircraft = aircraft

    @property
    def airline(self):
        """Gets the airline of this TimetableData.  # noqa: E501


        :return: The airline of this TimetableData.  # noqa: E501
        :rtype: TimetableAirline
        """
        return self._airline

    @airline.setter
    def airline(self, airline):
        """Sets the airline of this TimetableData.


        :param airline: The airline of this TimetableData.  # noqa: E501
        :type: TimetableAirline
        """

        self._airline = airline

    @property
    def arrival(self):
        """Gets the arrival of this TimetableData.  # noqa: E501


        :return: The arrival of this TimetableData.  # noqa: E501
        :rtype: TimetableSchedule
        """
        return self._arrival

    @arrival.setter
    def arrival(self, arrival):
        """Sets the arrival of this TimetableData.


        :param arrival: The arrival of this TimetableData.  # noqa: E501
        :type: TimetableSchedule
        """

        self._arrival = arrival

    @property
    def codeshared(self):
        """Gets the codeshared of this TimetableData.  # noqa: E501


        :return: The codeshared of this TimetableData.  # noqa: E501
        :rtype: TimetableDataCodeshared
        """
        return self._codeshared

    @codeshared.setter
    def codeshared(self, codeshared):
        """Sets the codeshared of this TimetableData.


        :param codeshared: The codeshared of this TimetableData.  # noqa: E501
        :type: TimetableDataCodeshared
        """

        self._codeshared = codeshared

    @property
    def departure(self):
        """Gets the departure of this TimetableData.  # noqa: E501


        :return: The departure of this TimetableData.  # noqa: E501
        :rtype: TimetableSchedule
        """
        return self._departure

    @departure.setter
    def departure(self, departure):
        """Sets the departure of this TimetableData.


        :param departure: The departure of this TimetableData.  # noqa: E501
        :type: TimetableSchedule
        """

        self._departure = departure

    @property
    def flight(self):
        """Gets the flight of this TimetableData.  # noqa: E501


        :return: The flight of this TimetableData.  # noqa: E501
        :rtype: TimetableFlight
        """
        return self._flight

    @flight.setter
    def flight(self, flight):
        """Sets the flight of this TimetableData.


        :param flight: The flight of this TimetableData.  # noqa: E501
        :type: TimetableFlight
        """

        self._flight = flight

    @property
    def status(self):
        """Gets the status of this TimetableData.  # noqa: E501


        :return: The status of this TimetableData.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this TimetableData.


        :param status: The status of this TimetableData.  # noqa: E501
        :type: str
        """

        self._status = status

    @property
    def type(self):
        """Gets the type of this TimetableData.  # noqa: E501


        :return: The type of this TimetableData.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this TimetableData.


        :param type: The type of this TimetableData.  # noqa: E501
        :type: str
        """

        self._type = type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TimetableData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TimetableData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
