# coding: utf-8

"""
    AviationStack

    The aviationstack API was built to provide a simple way of accessing global aviation data for real-time and historical flights as well as allow customers to tap into an extensive data set of airline routes and other up-to-date aviation-related information. Requests to the REST API are made using a straightforward HTTP GET URL structure and responses are provided in lightweight JSON format. The following API documentation can be applied for any major programming language and will present general integration guides and explanations around API endpoints, request parameters and response objects. If any questions remain unanswered for you, simply reach out to the aviationstack support team for assistance.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class TimetableFlight(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'iata_number': 'str',
        'icao_number': 'str',
        'number': 'str'
    }

    attribute_map = {
        'iata_number': 'iataNumber',
        'icao_number': 'icaoNumber',
        'number': 'number'
    }

    def __init__(self, iata_number=None, icao_number=None, number=None):  # noqa: E501
        """TimetableFlight - a model defined in Swagger"""  # noqa: E501
        self._iata_number = None
        self._icao_number = None
        self._number = None
        self.discriminator = None
        if iata_number is not None:
            self.iata_number = iata_number
        if icao_number is not None:
            self.icao_number = icao_number
        if number is not None:
            self.number = number

    @property
    def iata_number(self):
        """Gets the iata_number of this TimetableFlight.  # noqa: E501


        :return: The iata_number of this TimetableFlight.  # noqa: E501
        :rtype: str
        """
        return self._iata_number

    @iata_number.setter
    def iata_number(self, iata_number):
        """Sets the iata_number of this TimetableFlight.


        :param iata_number: The iata_number of this TimetableFlight.  # noqa: E501
        :type: str
        """

        self._iata_number = iata_number

    @property
    def icao_number(self):
        """Gets the icao_number of this TimetableFlight.  # noqa: E501


        :return: The icao_number of this TimetableFlight.  # noqa: E501
        :rtype: str
        """
        return self._icao_number

    @icao_number.setter
    def icao_number(self, icao_number):
        """Sets the icao_number of this TimetableFlight.


        :param icao_number: The icao_number of this TimetableFlight.  # noqa: E501
        :type: str
        """

        self._icao_number = icao_number

    @property
    def number(self):
        """Gets the number of this TimetableFlight.  # noqa: E501


        :return: The number of this TimetableFlight.  # noqa: E501
        :rtype: str
        """
        return self._number

    @number.setter
    def number(self, number):
        """Sets the number of this TimetableFlight.


        :param number: The number of this TimetableFlight.  # noqa: E501
        :type: str
        """

        self._number = number

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TimetableFlight, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TimetableFlight):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
