# coding: utf-8

"""
    AviationStack

    The aviationstack API was built to provide a simple way of accessing global aviation data for real-time and historical flights as well as allow customers to tap into an extensive data set of airline routes and other up-to-date aviation-related information. Requests to the REST API are made using a straightforward HTTP GET URL structure and responses are provided in lightweight JSON format. The following API documentation can be applied for any major programming language and will present general integration guides and explanations around API endpoints, request parameters and response objects. If any questions remain unanswered for you, simply reach out to the aviationstack support team for assistance.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class TimetableSchedule(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'actual_runway': 'str',
        'actual_time': 'str',
        'baggage': 'str',
        'delay': 'str',
        'estimated_runway': 'str',
        'estimated_time': 'str',
        'gate': 'str',
        'iata_code': 'str',
        'icao_code': 'str',
        'scheduled_time': 'str',
        'terminal': 'str'
    }

    attribute_map = {
        'actual_runway': 'actualRunway',
        'actual_time': 'actualTime',
        'baggage': 'baggage',
        'delay': 'delay',
        'estimated_runway': 'estimatedRunway',
        'estimated_time': 'estimatedTime',
        'gate': 'gate',
        'iata_code': 'iataCode',
        'icao_code': 'icaoCode',
        'scheduled_time': 'scheduledTime',
        'terminal': 'terminal'
    }

    def __init__(self, actual_runway=None, actual_time=None, baggage=None, delay=None, estimated_runway=None, estimated_time=None, gate=None, iata_code=None, icao_code=None, scheduled_time=None, terminal=None):  # noqa: E501
        """TimetableSchedule - a model defined in Swagger"""  # noqa: E501
        self._actual_runway = None
        self._actual_time = None
        self._baggage = None
        self._delay = None
        self._estimated_runway = None
        self._estimated_time = None
        self._gate = None
        self._iata_code = None
        self._icao_code = None
        self._scheduled_time = None
        self._terminal = None
        self.discriminator = None
        if actual_runway is not None:
            self.actual_runway = actual_runway
        if actual_time is not None:
            self.actual_time = actual_time
        if baggage is not None:
            self.baggage = baggage
        if delay is not None:
            self.delay = delay
        if estimated_runway is not None:
            self.estimated_runway = estimated_runway
        if estimated_time is not None:
            self.estimated_time = estimated_time
        if gate is not None:
            self.gate = gate
        if iata_code is not None:
            self.iata_code = iata_code
        if icao_code is not None:
            self.icao_code = icao_code
        if scheduled_time is not None:
            self.scheduled_time = scheduled_time
        if terminal is not None:
            self.terminal = terminal

    @property
    def actual_runway(self):
        """Gets the actual_runway of this TimetableSchedule.  # noqa: E501


        :return: The actual_runway of this TimetableSchedule.  # noqa: E501
        :rtype: str
        """
        return self._actual_runway

    @actual_runway.setter
    def actual_runway(self, actual_runway):
        """Sets the actual_runway of this TimetableSchedule.


        :param actual_runway: The actual_runway of this TimetableSchedule.  # noqa: E501
        :type: str
        """

        self._actual_runway = actual_runway

    @property
    def actual_time(self):
        """Gets the actual_time of this TimetableSchedule.  # noqa: E501


        :return: The actual_time of this TimetableSchedule.  # noqa: E501
        :rtype: str
        """
        return self._actual_time

    @actual_time.setter
    def actual_time(self, actual_time):
        """Sets the actual_time of this TimetableSchedule.


        :param actual_time: The actual_time of this TimetableSchedule.  # noqa: E501
        :type: str
        """

        self._actual_time = actual_time

    @property
    def baggage(self):
        """Gets the baggage of this TimetableSchedule.  # noqa: E501


        :return: The baggage of this TimetableSchedule.  # noqa: E501
        :rtype: str
        """
        return self._baggage

    @baggage.setter
    def baggage(self, baggage):
        """Sets the baggage of this TimetableSchedule.


        :param baggage: The baggage of this TimetableSchedule.  # noqa: E501
        :type: str
        """

        self._baggage = baggage

    @property
    def delay(self):
        """Gets the delay of this TimetableSchedule.  # noqa: E501


        :return: The delay of this TimetableSchedule.  # noqa: E501
        :rtype: str
        """
        return self._delay

    @delay.setter
    def delay(self, delay):
        """Sets the delay of this TimetableSchedule.


        :param delay: The delay of this TimetableSchedule.  # noqa: E501
        :type: str
        """

        self._delay = delay

    @property
    def estimated_runway(self):
        """Gets the estimated_runway of this TimetableSchedule.  # noqa: E501


        :return: The estimated_runway of this TimetableSchedule.  # noqa: E501
        :rtype: str
        """
        return self._estimated_runway

    @estimated_runway.setter
    def estimated_runway(self, estimated_runway):
        """Sets the estimated_runway of this TimetableSchedule.


        :param estimated_runway: The estimated_runway of this TimetableSchedule.  # noqa: E501
        :type: str
        """

        self._estimated_runway = estimated_runway

    @property
    def estimated_time(self):
        """Gets the estimated_time of this TimetableSchedule.  # noqa: E501


        :return: The estimated_time of this TimetableSchedule.  # noqa: E501
        :rtype: str
        """
        return self._estimated_time

    @estimated_time.setter
    def estimated_time(self, estimated_time):
        """Sets the estimated_time of this TimetableSchedule.


        :param estimated_time: The estimated_time of this TimetableSchedule.  # noqa: E501
        :type: str
        """

        self._estimated_time = estimated_time

    @property
    def gate(self):
        """Gets the gate of this TimetableSchedule.  # noqa: E501


        :return: The gate of this TimetableSchedule.  # noqa: E501
        :rtype: str
        """
        return self._gate

    @gate.setter
    def gate(self, gate):
        """Sets the gate of this TimetableSchedule.


        :param gate: The gate of this TimetableSchedule.  # noqa: E501
        :type: str
        """

        self._gate = gate

    @property
    def iata_code(self):
        """Gets the iata_code of this TimetableSchedule.  # noqa: E501


        :return: The iata_code of this TimetableSchedule.  # noqa: E501
        :rtype: str
        """
        return self._iata_code

    @iata_code.setter
    def iata_code(self, iata_code):
        """Sets the iata_code of this TimetableSchedule.


        :param iata_code: The iata_code of this TimetableSchedule.  # noqa: E501
        :type: str
        """

        self._iata_code = iata_code

    @property
    def icao_code(self):
        """Gets the icao_code of this TimetableSchedule.  # noqa: E501


        :return: The icao_code of this TimetableSchedule.  # noqa: E501
        :rtype: str
        """
        return self._icao_code

    @icao_code.setter
    def icao_code(self, icao_code):
        """Sets the icao_code of this TimetableSchedule.


        :param icao_code: The icao_code of this TimetableSchedule.  # noqa: E501
        :type: str
        """

        self._icao_code = icao_code

    @property
    def scheduled_time(self):
        """Gets the scheduled_time of this TimetableSchedule.  # noqa: E501


        :return: The scheduled_time of this TimetableSchedule.  # noqa: E501
        :rtype: str
        """
        return self._scheduled_time

    @scheduled_time.setter
    def scheduled_time(self, scheduled_time):
        """Sets the scheduled_time of this TimetableSchedule.


        :param scheduled_time: The scheduled_time of this TimetableSchedule.  # noqa: E501
        :type: str
        """

        self._scheduled_time = scheduled_time

    @property
    def terminal(self):
        """Gets the terminal of this TimetableSchedule.  # noqa: E501


        :return: The terminal of this TimetableSchedule.  # noqa: E501
        :rtype: str
        """
        return self._terminal

    @terminal.setter
    def terminal(self, terminal):
        """Sets the terminal of this TimetableSchedule.


        :param terminal: The terminal of this TimetableSchedule.  # noqa: E501
        :type: str
        """

        self._terminal = terminal

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TimetableSchedule, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TimetableSchedule):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
