-- ==============================================================================
-- AIRLINE DATA ENGINEERING PLATFORM - RELATIONAL DDL (PostgreSQL)
-- ==============================================================================

-- 1. GEOGRAPHIC & REFERENCE TABLES
CREATE TABLE IF NOT EXISTS countries (
    country_iso2 CHAR(2) PRIMARY KEY,
    country_name VARCHAR(100) NOT NULL,
    country_iso3 CHAR(3),
    continent CHAR(2),
    currency_code CHAR(3),
    capital VARCHAR(100),
    population BIGINT
);

CREATE TABLE IF NOT EXISTS cities (
    city_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city_name VARCHAR(100) NOT NULL,
    city_iata_code CHAR(3),
    country_iso2 CHAR(2) REFERENCES countries(country_iso2) ON DELETE SET NULL,
    latitude DECIMAL(9, 6),
    longitude DECIMAL(9, 6),
    timezone VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS airports (
    iata_code CHAR(3) PRIMARY KEY,
    icao_code CHAR(4),
    name VARCHAR(150) NOT NULL,
    city_id INT REFERENCES cities(city_id) ON DELETE SET NULL,
    country_iso2 CHAR(2) REFERENCES countries(country_iso2) ON DELETE SET NULL,
    city VARCHAR(100),
    country VARCHAR(100),
    latitude DECIMAL(9, 6),
    longitude DECIMAL(9, 6),
    timezone VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS airlines (
    airline_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    iata_code CHAR(2) UNIQUE NOT NULL,
    icao_code CHAR(3),
    name VARCHAR(150) NOT NULL,
    callsign VARCHAR(100),
    country_iso2 CHAR(2) REFERENCES countries(country_iso2) ON DELETE SET NULL,
    country VARCHAR(100),
    is_active BOOLEAN DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS airplane_models (
    model_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_code VARCHAR(50) UNIQUE NOT NULL,
    manufacturer VARCHAR(100) NOT NULL,
    seat_capacity INT,
    range_km INT,
    cruising_speed_kmh INT
);

CREATE TABLE IF NOT EXISTS airplanes (
    airplane_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tail_number VARCHAR(20) UNIQUE NOT NULL,
    airline_id INT NOT NULL REFERENCES airlines(airline_id) ON DELETE CASCADE,
    model_id INT REFERENCES airplane_models(model_id) ON DELETE SET NULL,
    manufacture_year INT,
    status VARCHAR(30) DEFAULT 'active'
);

-- 2. SCHEDULES & OPERATIONAL FLIGHTS
CREATE TABLE IF NOT EXISTS flight_schedules (
    schedule_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    flight_number VARCHAR(10) NOT NULL,
    airline_id INT NOT NULL REFERENCES airlines(airline_id) ON DELETE CASCADE,
    origin_iata CHAR(3) NOT NULL REFERENCES airports(iata_code) ON DELETE RESTRICT,
    destination_iata CHAR(3) NOT NULL REFERENCES airports(iata_code) ON DELETE RESTRICT,
    scheduled_departure_time TIME NOT NULL,
    scheduled_arrival_time TIME NOT NULL,
    days_of_week VARCHAR(7) DEFAULT '1234567',
    distance_km INT,
    UNIQUE (flight_number, airline_id, origin_iata, destination_iata)
);

CREATE TABLE IF NOT EXISTS flights (
    flight_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schedule_id INT REFERENCES flight_schedules(schedule_id) ON DELETE SET NULL,
    flight_date DATE NOT NULL,
    flight_number VARCHAR(10) NOT NULL,
    airplane_id INT REFERENCES airplanes(airplane_id) ON DELETE SET NULL,
    scheduled_departure TIMESTAMPTZ NOT NULL,
    actual_departure TIMESTAMPTZ,
    scheduled_arrival TIMESTAMPTZ NOT NULL,
    actual_arrival TIMESTAMPTZ,
    departure_delay_min INT DEFAULT 0,
    arrival_delay_min INT DEFAULT 0,
    status VARCHAR(30) DEFAULT 'scheduled',
    terminal_dep VARCHAR(10),
    gate_dep VARCHAR(10),
    terminal_arr VARCHAR(10),
    gate_arr VARCHAR(10),
    UNIQUE (flight_date, flight_number, scheduled_departure)
);

-- 3. PASSENGERS, BOOKINGS & ITINERARIES
CREATE TABLE IF NOT EXISTS passengers (
    passenger_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(150) UNIQUE NOT NULL,
    phone VARCHAR(30),
    passport_number VARCHAR(50),
    nationality CHAR(2) REFERENCES countries(country_iso2) ON DELETE SET NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS passenger_documents (
    document_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    passenger_id BIGINT NOT NULL REFERENCES passengers(passenger_id) ON DELETE CASCADE,
    document_type VARCHAR(20) NOT NULL DEFAULT 'passport', -- 'passport', 'national_id'
    document_number VARCHAR(50) NOT NULL,
    issuing_country CHAR(2) NOT NULL REFERENCES countries(country_iso2) ON DELETE RESTRICT,
    expiration_date DATE,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (document_type, document_number, issuing_country)
);

CREATE TABLE IF NOT EXISTS bookings (
    booking_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_reference VARCHAR(10) UNIQUE NOT NULL,
    passenger_id BIGINT NOT NULL REFERENCES passengers(passenger_id) ON DELETE CASCADE,
    document_id BIGINT REFERENCES passenger_documents(document_id) ON DELETE SET NULL,
    booking_timestamp TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    total_price DECIMAL(10, 2) NOT NULL,
    currency CHAR(3) DEFAULT 'EUR',
    status VARCHAR(30) DEFAULT 'confirmed'
);

CREATE TABLE IF NOT EXISTS itineraries (
    itinerary_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT NOT NULL REFERENCES bookings(booking_id) ON DELETE CASCADE,
    origin_iata CHAR(3) NOT NULL REFERENCES airports(iata_code) ON DELETE RESTRICT,
    destination_iata CHAR(3) NOT NULL REFERENCES airports(iata_code) ON DELETE RESTRICT,
    itinerary_type VARCHAR(30) NOT NULL, -- 'direct' or 'connecting_stopover'
    total_stops INT DEFAULT 0,
    total_duration_minutes INT,
    total_layover_minutes INT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS itinerary_segments (
    segment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    itinerary_id BIGINT NOT NULL REFERENCES itineraries(itinerary_id) ON DELETE CASCADE,
    segment_sequence INT NOT NULL, -- 1 for leg 1, 2 for leg 2, etc.
    flight_id BIGINT NOT NULL REFERENCES flights(flight_id) ON DELETE RESTRICT,
    seat_number VARCHAR(10),
    cabin_class VARCHAR(20) DEFAULT 'economy',
    layover_duration_minutes INT DEFAULT 0,
    boarding_pass_code VARCHAR(100),
    UNIQUE (itinerary_id, segment_sequence)
);

-- 4. PERFORMANCE & UNIQUE LOOKUP INDEXES
CREATE INDEX IF NOT EXISTS idx_cities_country ON cities(country_iso2);
CREATE INDEX IF NOT EXISTS idx_cities_iata ON cities(city_iata_code);
CREATE INDEX IF NOT EXISTS idx_airports_city_id ON airports(city_id);
CREATE INDEX IF NOT EXISTS idx_airports_country_iso ON airports(country_iso2);
CREATE INDEX IF NOT EXISTS idx_airports_icao ON airports(icao_code);
CREATE UNIQUE INDEX IF NOT EXISTS idx_airlines_icao_unique ON airlines(icao_code) WHERE icao_code IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_flights_date_number ON flights(flight_date, flight_number);
CREATE INDEX IF NOT EXISTS idx_flights_status ON flights(status);
CREATE INDEX IF NOT EXISTS idx_flights_scheduled_dep ON flights(scheduled_departure);
CREATE INDEX IF NOT EXISTS idx_schedules_route ON flight_schedules(origin_iata, destination_iata);
CREATE INDEX IF NOT EXISTS idx_itinerary_segments_flight ON itinerary_segments(flight_id);
CREATE INDEX IF NOT EXISTS idx_bookings_passenger ON bookings(passenger_id);

-- 5. ANALYTICAL ENRICHMENT VIEW: ENRICHED ITINERARIES
-- Computes itinerary travel journey, legs, carriers, and delay impact
DROP VIEW IF EXISTS v_enriched_itineraries;
CREATE VIEW v_enriched_itineraries AS
SELECT 
    b.booking_reference,
    p.first_name || ' ' || p.last_name AS passenger_name,
    p.email AS passenger_email,
    doc.document_type,
    doc.document_number,
    doc.issuing_country AS document_issuing_country,
    i.itinerary_id,
    i.itinerary_type,
    i.origin_iata AS journey_origin,
    COALESCE(c_orig.city_name, orig.city) AS origin_city,
    COALESCE(cn_orig.country_name, orig.country) AS origin_country,
    i.destination_iata AS journey_destination,
    COALESCE(c_dest.city_name, dest.city) AS destination_city,
    COALESCE(cn_dest.country_name, dest.country) AS destination_country,
    i.total_stops,
    seg.segment_sequence AS leg_number,
    f.flight_number,
    al.name AS airline_name,
    m.model_code AS aircraft_model,
    ap.tail_number AS aircraft_tail,
    f.scheduled_departure,
    f.actual_departure,
    f.departure_delay_min,
    f.scheduled_arrival,
    f.actual_arrival,
    f.arrival_delay_min,
    f.status AS flight_status,
    seg.seat_number,
    seg.cabin_class,
    seg.layover_duration_minutes
FROM bookings b
JOIN passengers p ON b.passenger_id = p.passenger_id
LEFT JOIN passenger_documents doc ON b.document_id = doc.document_id
JOIN itineraries i ON b.booking_id = i.booking_id
JOIN airports orig ON i.origin_iata = orig.iata_code
LEFT JOIN cities c_orig ON orig.city_id = c_orig.city_id
LEFT JOIN countries cn_orig ON orig.country_iso2 = cn_orig.country_iso2
JOIN airports dest ON i.destination_iata = dest.iata_code
LEFT JOIN cities c_dest ON dest.city_id = c_dest.city_id
LEFT JOIN countries cn_dest ON dest.country_iso2 = cn_dest.country_iso2
JOIN itinerary_segments seg ON i.itinerary_id = seg.itinerary_id
JOIN flights f ON seg.flight_id = f.flight_id
JOIN flight_schedules s ON f.schedule_id = s.schedule_id
JOIN airlines al ON s.airline_id = al.airline_id
LEFT JOIN airplanes ap ON f.airplane_id = ap.airplane_id
LEFT JOIN airplane_models m ON ap.model_id = m.model_id;
