# coding: utf-8

"""
    AviationStack

    The aviationstack API was built to provide a simple way of accessing global aviation data for real-time and historical flights as well as allow customers to tap into an extensive data set of airline routes and other up-to-date aviation-related information. Requests to the REST API are made using a straightforward HTTP GET URL structure and responses are provided in lightweight JSON format. The following API documentation can be applied for any major programming language and will present general integration guides and explanations around API endpoints, request parameters and response objects. If any questions remain unanswered for you, simply reach out to the aviationstack support team for assistance.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from swagger_client.api_client import ApiClient


class APIEndpointsApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def get_aircraft_types(self, access_key, **kwargs):  # noqa: E501
        """Aircraft Types  # noqa: E501

        To get data about different aircraft types, you can use the API's aircraft_types endpoint. Customers subscribed to the Basic Plan or higher may also make use of the search request parameter to get aircraft type autocomplete suggestions.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_aircraft_types(access_key, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str access_key: Your API access key, which can be found in your account dashboard. (required)
        :param str param_callback: Use this parameter to specify a JSONP callback function name to wrap your API response in.
        :param int limit: Specify a limit of results to return in your API response. Maximum allowed value is 100 below Professional Plan and 1000 on and above Professional Plan. Default value is 100.
        :param int offset: Specify an offset for pagination. Example: Specifying an offset of 10 in combination with a limit of 10 will show results 10-20. Default offset value is 0, starting with the first available result.
        :param str search: Use this parameter to get autocomplete suggestions by specifying any search term as a string. This feature is only available on the Basic Plan and higher.
        :return: AirCraftTypes
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_aircraft_types_with_http_info(access_key, **kwargs)  # noqa: E501
        else:
            (data) = self.get_aircraft_types_with_http_info(access_key, **kwargs)  # noqa: E501
            return data

    def get_aircraft_types_with_http_info(self, access_key, **kwargs):  # noqa: E501
        """Aircraft Types  # noqa: E501

        To get data about different aircraft types, you can use the API's aircraft_types endpoint. Customers subscribed to the Basic Plan or higher may also make use of the search request parameter to get aircraft type autocomplete suggestions.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_aircraft_types_with_http_info(access_key, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str access_key: Your API access key, which can be found in your account dashboard. (required)
        :param str param_callback: Use this parameter to specify a JSONP callback function name to wrap your API response in.
        :param int limit: Specify a limit of results to return in your API response. Maximum allowed value is 100 below Professional Plan and 1000 on and above Professional Plan. Default value is 100.
        :param int offset: Specify an offset for pagination. Example: Specifying an offset of 10 in combination with a limit of 10 will show results 10-20. Default offset value is 0, starting with the first available result.
        :param str search: Use this parameter to get autocomplete suggestions by specifying any search term as a string. This feature is only available on the Basic Plan and higher.
        :return: AirCraftTypes
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['access_key', 'param_callback', 'limit', 'offset', 'search']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_aircraft_types" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'access_key' is set
        if ('access_key' not in params or
                params['access_key'] is None):
            raise ValueError("Missing the required parameter `access_key` when calling `get_aircraft_types`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'access_key' in params:
            query_params.append(('access_key', params['access_key']))  # noqa: E501
        if 'param_callback' in params:
            query_params.append(('callback', params['param_callback']))  # noqa: E501
        if 'limit' in params:
            query_params.append(('limit', params['limit']))  # noqa: E501
        if 'offset' in params:
            query_params.append(('offset', params['offset']))  # noqa: E501
        if 'search' in params:
            query_params.append(('search', params['search']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['ApiKeyAuth']  # noqa: E501

        return self.api_client.call_api(
            '/v1/aircraft_types', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='AirCraftTypes',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_airlines(self, access_key, **kwargs):  # noqa: E501
        """Airlines.  # noqa: E501

        To get data about global airlines, you can use the API's airlines endpoint. Customers subscribed to the Basic Plan or higher may also make use of the search request parameter to get airline autocomplete suggestions.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_airlines(access_key, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str access_key: Your API access key, which can be found in your account dashboard. (required)
        :param str param_callback: Use this parameter to specify a JSONP callback function name to wrap your API response in.
        :param int limit: Specify a limit of results to return in your API response. Maximum allowed value is 100 below Professional Plan and 1000 on and above Professional Plan. Default value is 100.
        :param int offset: Specify an offset for pagination. Example: Specifying an offset of 10 in combination with a limit of 10 will show results 10-20. Default offset value is 0, starting with the first available result.
        :param str search: Use this parameter to get autocomplete suggestions by specifying any search term as a string. This feature is only available on the Basic Plan and higher.
        :return: AirLines
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_airlines_with_http_info(access_key, **kwargs)  # noqa: E501
        else:
            (data) = self.get_airlines_with_http_info(access_key, **kwargs)  # noqa: E501
            return data

    def get_airlines_with_http_info(self, access_key, **kwargs):  # noqa: E501
        """Airlines.  # noqa: E501

        To get data about global airlines, you can use the API's airlines endpoint. Customers subscribed to the Basic Plan or higher may also make use of the search request parameter to get airline autocomplete suggestions.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_airlines_with_http_info(access_key, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str access_key: Your API access key, which can be found in your account dashboard. (required)
        :param str param_callback: Use this parameter to specify a JSONP callback function name to wrap your API response in.
        :param int limit: Specify a limit of results to return in your API response. Maximum allowed value is 100 below Professional Plan and 1000 on and above Professional Plan. Default value is 100.
        :param int offset: Specify an offset for pagination. Example: Specifying an offset of 10 in combination with a limit of 10 will show results 10-20. Default offset value is 0, starting with the first available result.
        :param str search: Use this parameter to get autocomplete suggestions by specifying any search term as a string. This feature is only available on the Basic Plan and higher.
        :return: AirLines
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['access_key', 'param_callback', 'limit', 'offset', 'search']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_airlines" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'access_key' is set
        if ('access_key' not in params or
                params['access_key'] is None):
            raise ValueError("Missing the required parameter `access_key` when calling `get_airlines`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'access_key' in params:
            query_params.append(('access_key', params['access_key']))  # noqa: E501
        if 'param_callback' in params:
            query_params.append(('callback', params['param_callback']))  # noqa: E501
        if 'limit' in params:
            query_params.append(('limit', params['limit']))  # noqa: E501
        if 'offset' in params:
            query_params.append(('offset', params['offset']))  # noqa: E501
        if 'search' in params:
            query_params.append(('search', params['search']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['ApiKeyAuth']  # noqa: E501

        return self.api_client.call_api(
            '/v1/airlines', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='AirLines',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_airplanes(self, access_key, **kwargs):  # noqa: E501
        """AirPlanes.  # noqa: E501

        To get data about different airplanes/aircrafts, you can use the API's airplanes endpoint. Customers subscribed to the Basic Plan or higher may also make use of the search request parameter to get airplane autocomplete suggestions.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_airplanes(access_key, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str access_key: Your API access key, which can be found in your account dashboard. (required)
        :param str param_callback: Use this parameter to specify a JSONP callback function name to wrap your API response in.
        :param int limit: Specify a limit of results to return in your API response. Maximum allowed value is 100 below Professional Plan and 1000 on and above Professional Plan. Default value is 100.
        :param int offset: Specify an offset for pagination. Example: Specifying an offset of 10 in combination with a limit of 10 will show results 10-20. Default offset value is 0, starting with the first available result.
        :param str search: Use this parameter to get autocomplete suggestions by specifying any search term as a string. This feature is only available on the Basic Plan and higher.
        :return: AirPlanes
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_airplanes_with_http_info(access_key, **kwargs)  # noqa: E501
        else:
            (data) = self.get_airplanes_with_http_info(access_key, **kwargs)  # noqa: E501
            return data

    def get_airplanes_with_http_info(self, access_key, **kwargs):  # noqa: E501
        """AirPlanes.  # noqa: E501

        To get data about different airplanes/aircrafts, you can use the API's airplanes endpoint. Customers subscribed to the Basic Plan or higher may also make use of the search request parameter to get airplane autocomplete suggestions.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_airplanes_with_http_info(access_key, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str access_key: Your API access key, which can be found in your account dashboard. (required)
        :param str param_callback: Use this parameter to specify a JSONP callback function name to wrap your API response in.
        :param int limit: Specify a limit of results to return in your API response. Maximum allowed value is 100 below Professional Plan and 1000 on and above Professional Plan. Default value is 100.
        :param int offset: Specify an offset for pagination. Example: Specifying an offset of 10 in combination with a limit of 10 will show results 10-20. Default offset value is 0, starting with the first available result.
        :param str search: Use this parameter to get autocomplete suggestions by specifying any search term as a string. This feature is only available on the Basic Plan and higher.
        :return: AirPlanes
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['access_key', 'param_callback', 'limit', 'offset', 'search']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_airplanes" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'access_key' is set
        if ('access_key' not in params or
                params['access_key'] is None):
            raise ValueError("Missing the required parameter `access_key` when calling `get_airplanes`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'access_key' in params:
            query_params.append(('access_key', params['access_key']))  # noqa: E501
        if 'param_callback' in params:
            query_params.append(('callback', params['param_callback']))  # noqa: E501
        if 'limit' in params:
            query_params.append(('limit', params['limit']))  # noqa: E501
        if 'offset' in params:
            query_params.append(('offset', params['offset']))  # noqa: E501
        if 'search' in params:
            query_params.append(('search', params['search']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['ApiKeyAuth']  # noqa: E501

        return self.api_client.call_api(
            '/v1/airplanes', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='AirPlanes',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_airports(self, access_key, **kwargs):  # noqa: E501
        """Airports.  # noqa: E501

        To get data about global airports, you can use the API's airports endpoint. Customers subscribed to the Basic Plan or higher may also make use of the search request parameter to get airport autocomplete suggestions.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_airports(access_key, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str access_key: Your API access key, which can be found in your account dashboard. (required)
        :param str param_callback: Use this parameter to specify a JSONP callback function name to wrap your API response in.
        :param int limit: Specify a limit of results to return in your API response. Maximum allowed value is 100 below Professional Plan and 1000 on and above Professional Plan. Default value is 100.
        :param int offset: Specify an offset for pagination. Example: Specifying an offset of 10 in combination with a limit of 10 will show results 10-20. Default offset value is 0, starting with the first available result.
        :param str search: Use this parameter to get autocomplete suggestions by specifying any search term as a string. This feature is only available on the Basic Plan and higher.
        :return: Airports
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_airports_with_http_info(access_key, **kwargs)  # noqa: E501
        else:
            (data) = self.get_airports_with_http_info(access_key, **kwargs)  # noqa: E501
            return data

    def get_airports_with_http_info(self, access_key, **kwargs):  # noqa: E501
        """Airports.  # noqa: E501

        To get data about global airports, you can use the API's airports endpoint. Customers subscribed to the Basic Plan or higher may also make use of the search request parameter to get airport autocomplete suggestions.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_airports_with_http_info(access_key, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str access_key: Your API access key, which can be found in your account dashboard. (required)
        :param str param_callback: Use this parameter to specify a JSONP callback function name to wrap your API response in.
        :param int limit: Specify a limit of results to return in your API response. Maximum allowed value is 100 below Professional Plan and 1000 on and above Professional Plan. Default value is 100.
        :param int offset: Specify an offset for pagination. Example: Specifying an offset of 10 in combination with a limit of 10 will show results 10-20. Default offset value is 0, starting with the first available result.
        :param str search: Use this parameter to get autocomplete suggestions by specifying any search term as a string. This feature is only available on the Basic Plan and higher.
        :return: Airports
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['access_key', 'param_callback', 'limit', 'offset', 'search']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_airports" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'access_key' is set
        if ('access_key' not in params or
                params['access_key'] is None):
            raise ValueError("Missing the required parameter `access_key` when calling `get_airports`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'access_key' in params:
            query_params.append(('access_key', params['access_key']))  # noqa: E501
        if 'param_callback' in params:
            query_params.append(('callback', params['param_callback']))  # noqa: E501
        if 'limit' in params:
            query_params.append(('limit', params['limit']))  # noqa: E501
        if 'offset' in params:
            query_params.append(('offset', params['offset']))  # noqa: E501
        if 'search' in params:
            query_params.append(('search', params['search']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['ApiKeyAuth']  # noqa: E501

        return self.api_client.call_api(
            '/v1/airports', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='Airports',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_cities(self, access_key, **kwargs):  # noqa: E501
        """Cities  # noqa: E501

        To look up destination cities, you can use the API's cities endpoint. Customers subscribed to the Basic Plan or higher may also make use of the search request parameter to get city autocomplete suggestions.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_cities(access_key, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str access_key: Your API access key, which can be found in your account dashboard. (required)
        :param str param_callback: Use this parameter to specify a JSONP callback function name to wrap your API response in.
        :param int limit: Specify a limit of results to return in your API response. Maximum allowed value is 100 below Professional Plan and 1000 on and above Professional Plan. Default value is 100.
        :param int offset: Specify an offset for pagination. Example: Specifying an offset of 10 in combination with a limit of 10 will show results 10-20. Default offset value is 0, starting with the first available result.
        :param str search: Use this parameter to get autocomplete suggestions by specifying any search term as a string. This feature is only available on the Basic Plan and higher.
        :return: Cities
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_cities_with_http_info(access_key, **kwargs)  # noqa: E501
        else:
            (data) = self.get_cities_with_http_info(access_key, **kwargs)  # noqa: E501
            return data

    def get_cities_with_http_info(self, access_key, **kwargs):  # noqa: E501
        """Cities  # noqa: E501

        To look up destination cities, you can use the API's cities endpoint. Customers subscribed to the Basic Plan or higher may also make use of the search request parameter to get city autocomplete suggestions.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_cities_with_http_info(access_key, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str access_key: Your API access key, which can be found in your account dashboard. (required)
        :param str param_callback: Use this parameter to specify a JSONP callback function name to wrap your API response in.
        :param int limit: Specify a limit of results to return in your API response. Maximum allowed value is 100 below Professional Plan and 1000 on and above Professional Plan. Default value is 100.
        :param int offset: Specify an offset for pagination. Example: Specifying an offset of 10 in combination with a limit of 10 will show results 10-20. Default offset value is 0, starting with the first available result.
        :param str search: Use this parameter to get autocomplete suggestions by specifying any search term as a string. This feature is only available on the Basic Plan and higher.
        :return: Cities
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['access_key', 'param_callback', 'limit', 'offset', 'search']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_cities" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'access_key' is set
        if ('access_key' not in params or
                params['access_key'] is None):
            raise ValueError("Missing the required parameter `access_key` when calling `get_cities`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'access_key' in params:
            query_params.append(('access_key', params['access_key']))  # noqa: E501
        if 'param_callback' in params:
            query_params.append(('callback', params['param_callback']))  # noqa: E501
        if 'limit' in params:
            query_params.append(('limit', params['limit']))  # noqa: E501
        if 'offset' in params:
            query_params.append(('offset', params['offset']))  # noqa: E501
        if 'search' in params:
            query_params.append(('search', params['search']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['ApiKeyAuth']  # noqa: E501

        return self.api_client.call_api(
            '/v1/cities', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='Cities',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_countries(self, access_key, **kwargs):  # noqa: E501
        """Countries  # noqa: E501

        To look up destination countries, you can use the API's countries endpoint. Customers subscribed to the Basic Plan or higher may also make use of the search request parameter to get country autocomplete suggestions.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_countries(access_key, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str access_key: Your API access key, which can be found in your account dashboard. (required)
        :param str param_callback: Use this parameter to specify a JSONP callback function name to wrap your API response in.
        :param int limit: Specify a limit of results to return in your API response. Maximum allowed value is 100 below Professional Plan and 1000 on and above Professional Plan. Default value is 100.
        :param int offset: Specify an offset for pagination. Example: Specifying an offset of 10 in combination with a limit of 10 will show results 10-20. Default offset value is 0, starting with the first available result.
        :param str search: Use this parameter to get autocomplete suggestions by specifying any search term as a string. This feature is only available on the Basic Plan and higher.
        :return: Countries
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_countries_with_http_info(access_key, **kwargs)  # noqa: E501
        else:
            (data) = self.get_countries_with_http_info(access_key, **kwargs)  # noqa: E501
            return data

    def get_countries_with_http_info(self, access_key, **kwargs):  # noqa: E501
        """Countries  # noqa: E501

        To look up destination countries, you can use the API's countries endpoint. Customers subscribed to the Basic Plan or higher may also make use of the search request parameter to get country autocomplete suggestions.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_countries_with_http_info(access_key, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str access_key: Your API access key, which can be found in your account dashboard. (required)
        :param str param_callback: Use this parameter to specify a JSONP callback function name to wrap your API response in.
        :param int limit: Specify a limit of results to return in your API response. Maximum allowed value is 100 below Professional Plan and 1000 on and above Professional Plan. Default value is 100.
        :param int offset: Specify an offset for pagination. Example: Specifying an offset of 10 in combination with a limit of 10 will show results 10-20. Default offset value is 0, starting with the first available result.
        :param str search: Use this parameter to get autocomplete suggestions by specifying any search term as a string. This feature is only available on the Basic Plan and higher.
        :return: Countries
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['access_key', 'param_callback', 'limit', 'offset', 'search']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_countries" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'access_key' is set
        if ('access_key' not in params or
                params['access_key'] is None):
            raise ValueError("Missing the required parameter `access_key` when calling `get_countries`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'access_key' in params:
            query_params.append(('access_key', params['access_key']))  # noqa: E501
        if 'param_callback' in params:
            query_params.append(('callback', params['param_callback']))  # noqa: E501
        if 'limit' in params:
            query_params.append(('limit', params['limit']))  # noqa: E501
        if 'offset' in params:
            query_params.append(('offset', params['offset']))  # noqa: E501
        if 'search' in params:
            query_params.append(('search', params['search']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['ApiKeyAuth']  # noqa: E501

        return self.api_client.call_api(
            '/v1/countries', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='Countries',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_flight_schedule(self, access_key, iata_code, type, **kwargs):  # noqa: E501
        """Flight Schedules (Timetable).  # noqa: E501

        The API's timetable endpoint returns real-time flight schedules (departures and arrivals) for a given airport. Specify the airport IATA code and the schedule type (departure or arrival) you are interested in.      *      * **Note:** The `/timetable` and `/flightsFuture` endpoints have rate limits of 1 request every 10 seconds for Paid Plans and 1 request every 60 seconds for Free Plans, and exceeding these limits may result in throttling.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_flight_schedule(access_key, iata_code, type, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str access_key: Your API access key, which can be found in your account dashboard. (required)
        :param str iata_code: IATA code of the airport for which the flight schedule should be retrieved. Example: JFK (required)
        :param str type: The type of schedule to retrieve. Available values: departure, arrival (required)
        :param int limit: Specify a limit of results to return in your API response. Maximum allowed value is 100 below Professional Plan and 1000 on and above Professional Plan. Default value is 100.
        :param int offset: Specify an offset for pagination. Example: Specifying an offset of 10 in combination with a limit of 10 will show results 10-20. Default offset value is 0, starting with the first available result.
        :param str status: Filter your results by flight status. Available values: landed, scheduled, cancelled, active, incident, diverted, redirected, unknown
        :param str airline_name: Filter your results by airline name.
        :param str airline_iata: Filter your results by airline IATA code.
        :param str airline_icao: Filter your results by airline ICAO code.
        :param str flight_iata: Filter your results by flight IATA code.
        :param str flight_icao: Filter your results by flight ICAO code.
        :param str flight_num: Filter your results by flight number.
        :param str dep_terminal: Filter your results by departure terminal.
        :param int dep_delay: Filter your results by departure delay (minutes).
        :param datetime dep_sch_time: Filter your results by departure scheduled time.
        :param datetime dep_est_time: Filter your results by departure estimated time.
        :param datetime dep_act_time: Filter your results by departure actual time.
        :param datetime dep_est_runway: Filter your results by departure estimated runway time.
        :param datetime dep_act_runway: Filter your results by departure actual runway time.
        :param str arr_terminal: Filter your results by arrival terminal.
        :param int arr_delay: Filter your results by arrival delay (minutes).
        :param datetime arr_sch_time: Filter your results by arrival scheduled time.
        :param datetime arr_est_time: Filter your results by arrival estimated time.
        :param datetime arr_act_time: Filter your results by arrival actual time.
        :param datetime arr_est_runway: Filter your results by arrival estimated runway time.
        :param datetime arr_act_runway: Filter your results by arrival actual runway time.
        :param str param_callback: Use this parameter to specify a JSONP callback function name to wrap your API response in.
        :return: Timetable
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_flight_schedule_with_http_info(access_key, iata_code, type, **kwargs)  # noqa: E501
        else:
            (data) = self.get_flight_schedule_with_http_info(access_key, iata_code, type, **kwargs)  # noqa: E501
            return data

    def get_flight_schedule_with_http_info(self, access_key, iata_code, type, **kwargs):  # noqa: E501
        """Flight Schedules (Timetable).  # noqa: E501

        The API's timetable endpoint returns real-time flight schedules (departures and arrivals) for a given airport. Specify the airport IATA code and the schedule type (departure or arrival) you are interested in.      *      * **Note:** The `/timetable` and `/flightsFuture` endpoints have rate limits of 1 request every 10 seconds for Paid Plans and 1 request every 60 seconds for Free Plans, and exceeding these limits may result in throttling.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_flight_schedule_with_http_info(access_key, iata_code, type, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str access_key: Your API access key, which can be found in your account dashboard. (required)
        :param str iata_code: IATA code of the airport for which the flight schedule should be retrieved. Example: JFK (required)
        :param str type: The type of schedule to retrieve. Available values: departure, arrival (required)
        :param int limit: Specify a limit of results to return in your API response. Maximum allowed value is 100 below Professional Plan and 1000 on and above Professional Plan. Default value is 100.
        :param int offset: Specify an offset for pagination. Example: Specifying an offset of 10 in combination with a limit of 10 will show results 10-20. Default offset value is 0, starting with the first available result.
        :param str status: Filter your results by flight status. Available values: landed, scheduled, cancelled, active, incident, diverted, redirected, unknown
        :param str airline_name: Filter your results by airline name.
        :param str airline_iata: Filter your results by airline IATA code.
        :param str airline_icao: Filter your results by airline ICAO code.
        :param str flight_iata: Filter your results by flight IATA code.
        :param str flight_icao: Filter your results by flight ICAO code.
        :param str flight_num: Filter your results by flight number.
        :param str dep_terminal: Filter your results by departure terminal.
        :param int dep_delay: Filter your results by departure delay (minutes).
        :param datetime dep_sch_time: Filter your results by departure scheduled time.
        :param datetime dep_est_time: Filter your results by departure estimated time.
        :param datetime dep_act_time: Filter your results by departure actual time.
        :param datetime dep_est_runway: Filter your results by departure estimated runway time.
        :param datetime dep_act_runway: Filter your results by departure actual runway time.
        :param str arr_terminal: Filter your results by arrival terminal.
        :param int arr_delay: Filter your results by arrival delay (minutes).
        :param datetime arr_sch_time: Filter your results by arrival scheduled time.
        :param datetime arr_est_time: Filter your results by arrival estimated time.
        :param datetime arr_act_time: Filter your results by arrival actual time.
        :param datetime arr_est_runway: Filter your results by arrival estimated runway time.
        :param datetime arr_act_runway: Filter your results by arrival actual runway time.
        :param str param_callback: Use this parameter to specify a JSONP callback function name to wrap your API response in.
        :return: Timetable
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['access_key', 'iata_code', 'type', 'limit', 'offset', 'status', 'airline_name', 'airline_iata', 'airline_icao', 'flight_iata', 'flight_icao', 'flight_num', 'dep_terminal', 'dep_delay', 'dep_sch_time', 'dep_est_time', 'dep_act_time', 'dep_est_runway', 'dep_act_runway', 'arr_terminal', 'arr_delay', 'arr_sch_time', 'arr_est_time', 'arr_act_time', 'arr_est_runway', 'arr_act_runway', 'param_callback']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_flight_schedule" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'access_key' is set
        if ('access_key' not in params or
                params['access_key'] is None):
            raise ValueError("Missing the required parameter `access_key` when calling `get_flight_schedule`")  # noqa: E501
        # verify the required parameter 'iata_code' is set
        if ('iata_code' not in params or
                params['iata_code'] is None):
            raise ValueError("Missing the required parameter `iata_code` when calling `get_flight_schedule`")  # noqa: E501
        # verify the required parameter 'type' is set
        if ('type' not in params or
                params['type'] is None):
            raise ValueError("Missing the required parameter `type` when calling `get_flight_schedule`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'access_key' in params:
            query_params.append(('access_key', params['access_key']))  # noqa: E501
        if 'iata_code' in params:
            query_params.append(('iataCode', params['iata_code']))  # noqa: E501
        if 'type' in params:
            query_params.append(('type', params['type']))  # noqa: E501
        if 'limit' in params:
            query_params.append(('limit', params['limit']))  # noqa: E501
        if 'offset' in params:
            query_params.append(('offset', params['offset']))  # noqa: E501
        if 'status' in params:
            query_params.append(('status', params['status']))  # noqa: E501
        if 'airline_name' in params:
            query_params.append(('airline_name', params['airline_name']))  # noqa: E501
        if 'airline_iata' in params:
            query_params.append(('airline_iata', params['airline_iata']))  # noqa: E501
        if 'airline_icao' in params:
            query_params.append(('airline_icao', params['airline_icao']))  # noqa: E501
        if 'flight_iata' in params:
            query_params.append(('flight_iata', params['flight_iata']))  # noqa: E501
        if 'flight_icao' in params:
            query_params.append(('flight_icao', params['flight_icao']))  # noqa: E501
        if 'flight_num' in params:
            query_params.append(('flight_num', params['flight_num']))  # noqa: E501
        if 'dep_terminal' in params:
            query_params.append(('dep_terminal', params['dep_terminal']))  # noqa: E501
        if 'dep_delay' in params:
            query_params.append(('dep_delay', params['dep_delay']))  # noqa: E501
        if 'dep_sch_time' in params:
            query_params.append(('dep_schTime', params['dep_sch_time']))  # noqa: E501
        if 'dep_est_time' in params:
            query_params.append(('dep_estTime', params['dep_est_time']))  # noqa: E501
        if 'dep_act_time' in params:
            query_params.append(('dep_actTime', params['dep_act_time']))  # noqa: E501
        if 'dep_est_runway' in params:
            query_params.append(('dep_estRunway', params['dep_est_runway']))  # noqa: E501
        if 'dep_act_runway' in params:
            query_params.append(('dep_actRunway', params['dep_act_runway']))  # noqa: E501
        if 'arr_terminal' in params:
            query_params.append(('arr_terminal', params['arr_terminal']))  # noqa: E501
        if 'arr_delay' in params:
            query_params.append(('arr_delay', params['arr_delay']))  # noqa: E501
        if 'arr_sch_time' in params:
            query_params.append(('arr_schTime', params['arr_sch_time']))  # noqa: E501
        if 'arr_est_time' in params:
            query_params.append(('arr_estTime', params['arr_est_time']))  # noqa: E501
        if 'arr_act_time' in params:
            query_params.append(('arr_actTime', params['arr_act_time']))  # noqa: E501
        if 'arr_est_runway' in params:
            query_params.append(('arr_estRunway', params['arr_est_runway']))  # noqa: E501
        if 'arr_act_runway' in params:
            query_params.append(('arr_actRunway', params['arr_act_runway']))  # noqa: E501
        if 'param_callback' in params:
            query_params.append(('callback', params['param_callback']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['ApiKeyAuth']  # noqa: E501

        return self.api_client.call_api(
            '/v1/timetable', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='Timetable',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_flights(self, access_key, **kwargs):  # noqa: E501
        """Real-Time Flights and Historical Flights.  # noqa: E501

        # Real-Time Flights      * The API is capable of tracking flights and retrieving flight status information in real-time. In order to look up real-time information about one or multiple flights, you can use the API's flights endpoint together with optional parameters to filter your result set.      * # Historical Flights      * Apart from providing data about real-time flight, the API's flights endpoint is also capable of looking up data about historical flights. In order to request data about one or more past flights, simply attach the flight_date parameter to your API request URL and set it to a date of your choice.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_flights(access_key, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str access_key: Your API access key, which can be found in your account dashboard. (required)
        :param str param_callback: Use this parameter to specify a JSONP callback function name to wrap your API response in.
        :param int limit: Specify a limit of results to return in your API response. Maximum allowed value is 100 below Professional Plan and 1000 on and above Professional Plan. Default value is 100.
        :param int offset: Specify an offset for pagination. Example: Specifying an offset of 10 in combination with a limit of 10 will show results 10-20. Default offset value is 0, starting with the first available result.
        :param str flight_status: Filter your results by flight status. Available values: scheduled, active, landed, cancelled, incident, diverted
        :param date flight_date: Filter your results by providing a flight date in the format YYYY-MM-DD. Example: 2019-02-31      *      * **Note:** Aviationstack provides historical data for the last 12 months only.      *      * **Note:** The API response returned for historical flights is identical to the API response returned for real-time flight data. To see the API response, please jump to the Real-Time Flights section.
        :param str dep_iata: Filter your results by departure city or airport using an IATA code. You can retrieve IATA codes using the Airports or Cities API endpoints.
        :param str arr_iata: Filter your results by arrival city or airport using an IATA code. You can retrieve IATA codes using the Airports or Cities API endpoints.
        :param str dep_icao: Filter your results by departure airport using an ICAO code. You can retrieve ICAO codes using the Airports API endpoint.
        :param str arr_icao: Filter your results by arrival airport using an ICAO code. You can retrieve ICAO codes using the Airports API endpoint.
        :param str airline_name: Filter your results by airline name. You can retrieve airline names using the Airlines API endpoint.
        :param str airline_iata: Filter your results by airline IATA code. You can retrieve airline IATA codes using the Airlines API endpoint.
        :param str airline_icao: Filter your results by airline ICAO code. You can retrieve airline ICAO codes using the Airlines API endpoint.
        :param str flight_number: Filter your results by providing a flight number. Example: 2557.
        :param str flight_iata: Filter your results by providing a flight IATA code. Example: MU2557.
        :param str flight_icao: Filter your results by providing a flight ICAO code. Example: CES2557.
        :param int min_delay_dep: Filter your results by providing a minimum amount of minutes in departure delay. Example: 7 for seven minutes of delay in departure.
        :param int min_delay_arr: Filter your results by providing a minimum amount of minutes in arrival delay. Example: 7 for seven minutes of delay in arrival.
        :param int max_delay_dep: Filter your results by providing a maximum amount of minutes in departure delay. Example: 60 for one hour of delay in departure.
        :param int max_delay_arr: Filter your results by providing a maximum amount of minutes in arrival delay. Example: 60 for one hour of delay in arrival.
        :param date arr_scheduled_time_arr: Filter your results by arrival scheduled date. [Format: YYYY-MM-DD]
        :param date dep_scheduled_time_dep: Filter your results by departure scheduled date. [Format: YYYY-MM-DD]
        :return: Flights
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_flights_with_http_info(access_key, **kwargs)  # noqa: E501
        else:
            (data) = self.get_flights_with_http_info(access_key, **kwargs)  # noqa: E501
            return data

    def get_flights_with_http_info(self, access_key, **kwargs):  # noqa: E501
        """Real-Time Flights and Historical Flights.  # noqa: E501

        # Real-Time Flights      * The API is capable of tracking flights and retrieving flight status information in real-time. In order to look up real-time information about one or multiple flights, you can use the API's flights endpoint together with optional parameters to filter your result set.      * # Historical Flights      * Apart from providing data about real-time flight, the API's flights endpoint is also capable of looking up data about historical flights. In order to request data about one or more past flights, simply attach the flight_date parameter to your API request URL and set it to a date of your choice.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_flights_with_http_info(access_key, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str access_key: Your API access key, which can be found in your account dashboard. (required)
        :param str param_callback: Use this parameter to specify a JSONP callback function name to wrap your API response in.
        :param int limit: Specify a limit of results to return in your API response. Maximum allowed value is 100 below Professional Plan and 1000 on and above Professional Plan. Default value is 100.
        :param int offset: Specify an offset for pagination. Example: Specifying an offset of 10 in combination with a limit of 10 will show results 10-20. Default offset value is 0, starting with the first available result.
        :param str flight_status: Filter your results by flight status. Available values: scheduled, active, landed, cancelled, incident, diverted
        :param date flight_date: Filter your results by providing a flight date in the format YYYY-MM-DD. Example: 2019-02-31      *      * **Note:** Aviationstack provides historical data for the last 12 months only.      *      * **Note:** The API response returned for historical flights is identical to the API response returned for real-time flight data. To see the API response, please jump to the Real-Time Flights section.
        :param str dep_iata: Filter your results by departure city or airport using an IATA code. You can retrieve IATA codes using the Airports or Cities API endpoints.
        :param str arr_iata: Filter your results by arrival city or airport using an IATA code. You can retrieve IATA codes using the Airports or Cities API endpoints.
        :param str dep_icao: Filter your results by departure airport using an ICAO code. You can retrieve ICAO codes using the Airports API endpoint.
        :param str arr_icao: Filter your results by arrival airport using an ICAO code. You can retrieve ICAO codes using the Airports API endpoint.
        :param str airline_name: Filter your results by airline name. You can retrieve airline names using the Airlines API endpoint.
        :param str airline_iata: Filter your results by airline IATA code. You can retrieve airline IATA codes using the Airlines API endpoint.
        :param str airline_icao: Filter your results by airline ICAO code. You can retrieve airline ICAO codes using the Airlines API endpoint.
        :param str flight_number: Filter your results by providing a flight number. Example: 2557.
        :param str flight_iata: Filter your results by providing a flight IATA code. Example: MU2557.
        :param str flight_icao: Filter your results by providing a flight ICAO code. Example: CES2557.
        :param int min_delay_dep: Filter your results by providing a minimum amount of minutes in departure delay. Example: 7 for seven minutes of delay in departure.
        :param int min_delay_arr: Filter your results by providing a minimum amount of minutes in arrival delay. Example: 7 for seven minutes of delay in arrival.
        :param int max_delay_dep: Filter your results by providing a maximum amount of minutes in departure delay. Example: 60 for one hour of delay in departure.
        :param int max_delay_arr: Filter your results by providing a maximum amount of minutes in arrival delay. Example: 60 for one hour of delay in arrival.
        :param date arr_scheduled_time_arr: Filter your results by arrival scheduled date. [Format: YYYY-MM-DD]
        :param date dep_scheduled_time_dep: Filter your results by departure scheduled date. [Format: YYYY-MM-DD]
        :return: Flights
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['access_key', 'param_callback', 'limit', 'offset', 'flight_status', 'flight_date', 'dep_iata', 'arr_iata', 'dep_icao', 'arr_icao', 'airline_name', 'airline_iata', 'airline_icao', 'flight_number', 'flight_iata', 'flight_icao', 'min_delay_dep', 'min_delay_arr', 'max_delay_dep', 'max_delay_arr', 'arr_scheduled_time_arr', 'dep_scheduled_time_dep']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_flights" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'access_key' is set
        if ('access_key' not in params or
                params['access_key'] is None):
            raise ValueError("Missing the required parameter `access_key` when calling `get_flights`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'access_key' in params:
            query_params.append(('access_key', params['access_key']))  # noqa: E501
        if 'param_callback' in params:
            query_params.append(('callback', params['param_callback']))  # noqa: E501
        if 'limit' in params:
            query_params.append(('limit', params['limit']))  # noqa: E501
        if 'offset' in params:
            query_params.append(('offset', params['offset']))  # noqa: E501
        if 'flight_status' in params:
            query_params.append(('flight_status', params['flight_status']))  # noqa: E501
        if 'flight_date' in params:
            query_params.append(('flight_date', params['flight_date']))  # noqa: E501
        if 'dep_iata' in params:
            query_params.append(('dep_iata', params['dep_iata']))  # noqa: E501
        if 'arr_iata' in params:
            query_params.append(('arr_iata', params['arr_iata']))  # noqa: E501
        if 'dep_icao' in params:
            query_params.append(('dep_icao', params['dep_icao']))  # noqa: E501
        if 'arr_icao' in params:
            query_params.append(('arr_icao', params['arr_icao']))  # noqa: E501
        if 'airline_name' in params:
            query_params.append(('airline_name', params['airline_name']))  # noqa: E501
        if 'airline_iata' in params:
            query_params.append(('airline_iata', params['airline_iata']))  # noqa: E501
        if 'airline_icao' in params:
            query_params.append(('airline_icao', params['airline_icao']))  # noqa: E501
        if 'flight_number' in params:
            query_params.append(('flight_number', params['flight_number']))  # noqa: E501
        if 'flight_iata' in params:
            query_params.append(('flight_iata', params['flight_iata']))  # noqa: E501
        if 'flight_icao' in params:
            query_params.append(('flight_icao', params['flight_icao']))  # noqa: E501
        if 'min_delay_dep' in params:
            query_params.append(('min_delay_dep', params['min_delay_dep']))  # noqa: E501
        if 'min_delay_arr' in params:
            query_params.append(('min_delay_arr', params['min_delay_arr']))  # noqa: E501
        if 'max_delay_dep' in params:
            query_params.append(('max_delay_dep', params['max_delay_dep']))  # noqa: E501
        if 'max_delay_arr' in params:
            query_params.append(('max_delay_arr', params['max_delay_arr']))  # noqa: E501
        if 'arr_scheduled_time_arr' in params:
            query_params.append(('arr_scheduled_time_arr', params['arr_scheduled_time_arr']))  # noqa: E501
        if 'dep_scheduled_time_dep' in params:
            query_params.append(('dep_scheduled_time_dep', params['dep_scheduled_time_dep']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['ApiKeyAuth']  # noqa: E501

        return self.api_client.call_api(
            '/v1/flights', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='Flights',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_future_flights(self, access_key, iata_code, type, _date, **kwargs):  # noqa: E501
        """Future Flight Schedules.  # noqa: E501

        The API's flightsFuture endpoint returns flight schedules for a future date. Specify the airport IATA code, the schedule type (departure or arrival) and the date you are interested in.      *      * **Note:** Flight blocks within a codeshared block take precedence over those outside it for filtering purposes. So, if there is a flight block inside codeshared, then it will search the query param to match in this `codeshared>flight>iataNumber`. If codeshared block is not present then it will refer to the `flight>iataNumber`.      *      * **Note:** The `/timetable` and `/flightsFuture` endpoints have rate limits of 1 request every 10 seconds for Paid Plans and 1 request every 60 seconds for Free Plans, and exceeding these limits may result in throttling. Also, we do not include very low-traffic airports (like CDT, which has around 10 or fewer flights per day) in our feeds.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_future_flights(access_key, iata_code, type, _date, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str access_key: Your API access key, which can be found in your account dashboard. (required)
        :param str iata_code: IATA code of the airport for which the future flight schedule should be retrieved. Example: JFK (required)
        :param str type: The type of schedule to retrieve. Available values: departure, arrival (required)
        :param date _date: The future date for which the flight schedule should be retrieved, in the format YYYY-MM-DD. (required)
        :param str airline_iata: Filter your results by airline IATA code.
        :param str airline_icao: Filter your results by airline ICAO code.
        :param str flight_number: Filter your results by flight number.
        :param int limit: Specify a limit of results to return in your API response. Maximum allowed value is 100 below Professional Plan and 1000 on and above Professional Plan. Default value is 100.
        :param int offset: Specify an offset for pagination. Example: Specifying an offset of 10 in combination with a limit of 10 will show results 10-20. Default offset value is 0, starting with the first available result.
        :param str param_callback: Use this parameter to specify a JSONP callback function name to wrap your API response in.
        :return: FlightsFuture
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_future_flights_with_http_info(access_key, iata_code, type, _date, **kwargs)  # noqa: E501
        else:
            (data) = self.get_future_flights_with_http_info(access_key, iata_code, type, _date, **kwargs)  # noqa: E501
            return data

    def get_future_flights_with_http_info(self, access_key, iata_code, type, _date, **kwargs):  # noqa: E501
        """Future Flight Schedules.  # noqa: E501

        The API's flightsFuture endpoint returns flight schedules for a future date. Specify the airport IATA code, the schedule type (departure or arrival) and the date you are interested in.      *      * **Note:** Flight blocks within a codeshared block take precedence over those outside it for filtering purposes. So, if there is a flight block inside codeshared, then it will search the query param to match in this `codeshared>flight>iataNumber`. If codeshared block is not present then it will refer to the `flight>iataNumber`.      *      * **Note:** The `/timetable` and `/flightsFuture` endpoints have rate limits of 1 request every 10 seconds for Paid Plans and 1 request every 60 seconds for Free Plans, and exceeding these limits may result in throttling. Also, we do not include very low-traffic airports (like CDT, which has around 10 or fewer flights per day) in our feeds.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_future_flights_with_http_info(access_key, iata_code, type, _date, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str access_key: Your API access key, which can be found in your account dashboard. (required)
        :param str iata_code: IATA code of the airport for which the future flight schedule should be retrieved. Example: JFK (required)
        :param str type: The type of schedule to retrieve. Available values: departure, arrival (required)
        :param date _date: The future date for which the flight schedule should be retrieved, in the format YYYY-MM-DD. (required)
        :param str airline_iata: Filter your results by airline IATA code.
        :param str airline_icao: Filter your results by airline ICAO code.
        :param str flight_number: Filter your results by flight number.
        :param int limit: Specify a limit of results to return in your API response. Maximum allowed value is 100 below Professional Plan and 1000 on and above Professional Plan. Default value is 100.
        :param int offset: Specify an offset for pagination. Example: Specifying an offset of 10 in combination with a limit of 10 will show results 10-20. Default offset value is 0, starting with the first available result.
        :param str param_callback: Use this parameter to specify a JSONP callback function name to wrap your API response in.
        :return: FlightsFuture
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['access_key', 'iata_code', 'type', '_date', 'airline_iata', 'airline_icao', 'flight_number', 'limit', 'offset', 'param_callback']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_future_flights" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'access_key' is set
        if ('access_key' not in params or
                params['access_key'] is None):
            raise ValueError("Missing the required parameter `access_key` when calling `get_future_flights`")  # noqa: E501
        # verify the required parameter 'iata_code' is set
        if ('iata_code' not in params or
                params['iata_code'] is None):
            raise ValueError("Missing the required parameter `iata_code` when calling `get_future_flights`")  # noqa: E501
        # verify the required parameter 'type' is set
        if ('type' not in params or
                params['type'] is None):
            raise ValueError("Missing the required parameter `type` when calling `get_future_flights`")  # noqa: E501
        # verify the required parameter '_date' is set
        if ('_date' not in params or
                params['_date'] is None):
            raise ValueError("Missing the required parameter `_date` when calling `get_future_flights`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'access_key' in params:
            query_params.append(('access_key', params['access_key']))  # noqa: E501
        if 'iata_code' in params:
            query_params.append(('iataCode', params['iata_code']))  # noqa: E501
        if 'type' in params:
            query_params.append(('type', params['type']))  # noqa: E501
        if '_date' in params:
            query_params.append(('date', params['_date']))  # noqa: E501
        if 'airline_iata' in params:
            query_params.append(('airline_iata', params['airline_iata']))  # noqa: E501
        if 'airline_icao' in params:
            query_params.append(('airline_icao', params['airline_icao']))  # noqa: E501
        if 'flight_number' in params:
            query_params.append(('flight_number', params['flight_number']))  # noqa: E501
        if 'limit' in params:
            query_params.append(('limit', params['limit']))  # noqa: E501
        if 'offset' in params:
            query_params.append(('offset', params['offset']))  # noqa: E501
        if 'param_callback' in params:
            query_params.append(('callback', params['param_callback']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['ApiKeyAuth']  # noqa: E501

        return self.api_client.call_api(
            '/v1/flightsFuture', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='FlightsFuture',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_routes(self, access_key, **kwargs):  # noqa: E501
        """Airline Routes.  # noqa: E501

        The aviationstack API is capable of providing data about airline routes, updated every 24 hours. In order to get airline route data, use the API's routes endpoint along with a series of optional parameters to filter results.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_routes(access_key, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str access_key: Your API access key, which can be found in your account dashboard. (required)
        :param str param_callback: Use this parameter to specify a JSONP callback function name to wrap your API response in.
        :param int limit: Specify a limit of results to return in your API response. Maximum allowed value is 100 below Professional Plan and 1000 on and above Professional Plan. Default value is 100.
        :param int offset: Specify an offset for pagination. Example: Specifying an offset of 10 in combination with a limit of 10 will show results 10-20. Default offset value is 0, starting with the first available result.
        :param str flight_number: Filter your results by providing a flight number. Example: 2557
        :param str dep_iata: Filter your results by departure city or airport using an IATA code. You can retrieve IATA codes using the Airports or Cities API endpoints.
        :param str arr_iata: Filter your results by arrival city or airport using an IATA code. You can retrieve IATA codes using the Airports or Cities API endpoints.
        :param str dep_icao: Filter your results by departure airport using an ICAO code. You can retrieve ICAO codes using the Airports API endpoint.
        :param str arr_icao: Filter your results by arrival airport using an ICAO code. You can retrieve ICAO codes using the Airports API endpoint.
        :param str airline_iata: Filter your results by airline IATA code. You can retrieve airline IATA codes using the Airlines API endpoint.
        :param str airline_icao: Filter your results by airline ICAO code. You can retrieve airline ICAO codes using the Airlines API endpoint.
        :return: Routes
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_routes_with_http_info(access_key, **kwargs)  # noqa: E501
        else:
            (data) = self.get_routes_with_http_info(access_key, **kwargs)  # noqa: E501
            return data

    def get_routes_with_http_info(self, access_key, **kwargs):  # noqa: E501
        """Airline Routes.  # noqa: E501

        The aviationstack API is capable of providing data about airline routes, updated every 24 hours. In order to get airline route data, use the API's routes endpoint along with a series of optional parameters to filter results.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_routes_with_http_info(access_key, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str access_key: Your API access key, which can be found in your account dashboard. (required)
        :param str param_callback: Use this parameter to specify a JSONP callback function name to wrap your API response in.
        :param int limit: Specify a limit of results to return in your API response. Maximum allowed value is 100 below Professional Plan and 1000 on and above Professional Plan. Default value is 100.
        :param int offset: Specify an offset for pagination. Example: Specifying an offset of 10 in combination with a limit of 10 will show results 10-20. Default offset value is 0, starting with the first available result.
        :param str flight_number: Filter your results by providing a flight number. Example: 2557
        :param str dep_iata: Filter your results by departure city or airport using an IATA code. You can retrieve IATA codes using the Airports or Cities API endpoints.
        :param str arr_iata: Filter your results by arrival city or airport using an IATA code. You can retrieve IATA codes using the Airports or Cities API endpoints.
        :param str dep_icao: Filter your results by departure airport using an ICAO code. You can retrieve ICAO codes using the Airports API endpoint.
        :param str arr_icao: Filter your results by arrival airport using an ICAO code. You can retrieve ICAO codes using the Airports API endpoint.
        :param str airline_iata: Filter your results by airline IATA code. You can retrieve airline IATA codes using the Airlines API endpoint.
        :param str airline_icao: Filter your results by airline ICAO code. You can retrieve airline ICAO codes using the Airlines API endpoint.
        :return: Routes
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['access_key', 'param_callback', 'limit', 'offset', 'flight_number', 'dep_iata', 'arr_iata', 'dep_icao', 'arr_icao', 'airline_iata', 'airline_icao']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_routes" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'access_key' is set
        if ('access_key' not in params or
                params['access_key'] is None):
            raise ValueError("Missing the required parameter `access_key` when calling `get_routes`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'access_key' in params:
            query_params.append(('access_key', params['access_key']))  # noqa: E501
        if 'param_callback' in params:
            query_params.append(('callback', params['param_callback']))  # noqa: E501
        if 'limit' in params:
            query_params.append(('limit', params['limit']))  # noqa: E501
        if 'offset' in params:
            query_params.append(('offset', params['offset']))  # noqa: E501
        if 'flight_number' in params:
            query_params.append(('flight_number', params['flight_number']))  # noqa: E501
        if 'dep_iata' in params:
            query_params.append(('dep_iata', params['dep_iata']))  # noqa: E501
        if 'arr_iata' in params:
            query_params.append(('arr_iata', params['arr_iata']))  # noqa: E501
        if 'dep_icao' in params:
            query_params.append(('dep_icao', params['dep_icao']))  # noqa: E501
        if 'arr_icao' in params:
            query_params.append(('arr_icao', params['arr_icao']))  # noqa: E501
        if 'airline_iata' in params:
            query_params.append(('airline_iata', params['airline_iata']))  # noqa: E501
        if 'airline_icao' in params:
            query_params.append(('airline_icao', params['airline_icao']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['ApiKeyAuth']  # noqa: E501

        return self.api_client.call_api(
            '/v1/routes', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='Routes',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_taxes(self, access_key, **kwargs):  # noqa: E501
        """Aviation Taxes  # noqa: E501

        To get data about aviation taxes, you can use the API's taxes endpoint. Customers subscribed to the Basic Plan or higher may also make use of the search request parameter to get autocomplete suggestions.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_taxes(access_key, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str access_key: Your API access key, which can be found in your account dashboard. (required)
        :param str param_callback: Use this parameter to specify a JSONP callback function name to wrap your API response in.
        :param int limit: Specify a limit of results to return in your API response. Maximum allowed value is 100 below Professional Plan and 1000 on and above Professional Plan. Default value is 100.
        :param int offset: Specify an offset for pagination. Example: Specifying an offset of 10 in combination with a limit of 10 will show results 10-20. Default offset value is 0, starting with the first available result.
        :param str search: Use this parameter to get autocomplete suggestions by specifying any search term as a string. This feature is only available on the Basic Plan and higher.
        :return: Taxes
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_taxes_with_http_info(access_key, **kwargs)  # noqa: E501
        else:
            (data) = self.get_taxes_with_http_info(access_key, **kwargs)  # noqa: E501
            return data

    def get_taxes_with_http_info(self, access_key, **kwargs):  # noqa: E501
        """Aviation Taxes  # noqa: E501

        To get data about aviation taxes, you can use the API's taxes endpoint. Customers subscribed to the Basic Plan or higher may also make use of the search request parameter to get autocomplete suggestions.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_taxes_with_http_info(access_key, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str access_key: Your API access key, which can be found in your account dashboard. (required)
        :param str param_callback: Use this parameter to specify a JSONP callback function name to wrap your API response in.
        :param int limit: Specify a limit of results to return in your API response. Maximum allowed value is 100 below Professional Plan and 1000 on and above Professional Plan. Default value is 100.
        :param int offset: Specify an offset for pagination. Example: Specifying an offset of 10 in combination with a limit of 10 will show results 10-20. Default offset value is 0, starting with the first available result.
        :param str search: Use this parameter to get autocomplete suggestions by specifying any search term as a string. This feature is only available on the Basic Plan and higher.
        :return: Taxes
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['access_key', 'param_callback', 'limit', 'offset', 'search']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_taxes" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'access_key' is set
        if ('access_key' not in params or
                params['access_key'] is None):
            raise ValueError("Missing the required parameter `access_key` when calling `get_taxes`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'access_key' in params:
            query_params.append(('access_key', params['access_key']))  # noqa: E501
        if 'param_callback' in params:
            query_params.append(('callback', params['param_callback']))  # noqa: E501
        if 'limit' in params:
            query_params.append(('limit', params['limit']))  # noqa: E501
        if 'offset' in params:
            query_params.append(('offset', params['offset']))  # noqa: E501
        if 'search' in params:
            query_params.append(('search', params['search']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['ApiKeyAuth']  # noqa: E501

        return self.api_client.call_api(
            '/v1/taxes', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='Taxes',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
