# coding: utf-8

"""
    AviationStack

    The aviationstack API was built to provide a simple way of accessing global aviation data for real-time and historical flights as well as allow customers to tap into an extensive data set of airline routes and other up-to-date aviation-related information. Requests to the REST API are made using a straightforward HTTP GET URL structure and responses are provided in lightweight JSON format. The following API documentation can be applied for any major programming language and will present general integration guides and explanations around API endpoints, request parameters and response objects. If any questions remain unanswered for you, simply reach out to the aviationstack support team for assistance.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.air_planes import AirPlanes  # noqa: E501
from swagger_client.rest import ApiException


class TestAirPlanes(unittest.TestCase):
    """AirPlanes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAirPlanes(self):
        """Test AirPlanes"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.air_planes.AirPlanes()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
