# coding: utf-8

"""
    AviationStack

    The aviationstack API was built to provide a simple way of accessing global aviation data for real-time and historical flights as well as allow customers to tap into an extensive data set of airline routes and other up-to-date aviation-related information. Requests to the REST API are made using a straightforward HTTP GET URL structure and responses are provided in lightweight JSON format. The following API documentation can be applied for any major programming language and will present general integration guides and explanations around API endpoints, request parameters and response objects. If any questions remain unanswered for you, simply reach out to the aviationstack support team for assistance.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.api_endpoints_api import APIEndpointsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAPIEndpointsApi(unittest.TestCase):
    """APIEndpointsApi unit test stubs"""

    def setUp(self):
        self.api = APIEndpointsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_aircraft_types(self):
        """Test case for get_aircraft_types

        Aircraft Types  # noqa: E501
        """
        pass

    def test_get_airlines(self):
        """Test case for get_airlines

        Airlines.  # noqa: E501
        """
        pass

    def test_get_airplanes(self):
        """Test case for get_airplanes

        AirPlanes.  # noqa: E501
        """
        pass

    def test_get_airports(self):
        """Test case for get_airports

        Airports.  # noqa: E501
        """
        pass

    def test_get_cities(self):
        """Test case for get_cities

        Cities  # noqa: E501
        """
        pass

    def test_get_countries(self):
        """Test case for get_countries

        Countries  # noqa: E501
        """
        pass

    def test_get_flight_schedule(self):
        """Test case for get_flight_schedule

        Flight Schedules (Timetable).  # noqa: E501
        """
        pass

    def test_get_flights(self):
        """Test case for get_flights

        Real-Time Flights and Historical Flights.  # noqa: E501
        """
        pass

    def test_get_future_flights(self):
        """Test case for get_future_flights

        Future Flight Schedules.  # noqa: E501
        """
        pass

    def test_get_routes(self):
        """Test case for get_routes

        Airline Routes.  # noqa: E501
        """
        pass

    def test_get_taxes(self):
        """Test case for get_taxes

        Aviation Taxes  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
